# Generated by Django 2.2.17 on 2026-09-01 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0049_structuremodel_model_type'),
        ('table_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpcrStructureBrowserTable',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='browser_row', serialize=False, to='structure.Structure')),
                ('coverage', models.IntegerField(null=True)),
                ('sodium_site', models.BooleanField(default=False)),
                ('fusions', models.TextField(null=True)),
                ('antibodies', models.TextField(null=True)),
                ('ligands', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('ligand_type', models.TextField(null=True)),
                ('ligand_role', models.TextField(null=True)),
                ('endo_ligands', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('endo_type', models.TextField(null=True)),
                ('gene_name', models.CharField(max_length=100, null=True)),
                ('gene_entrez_url', models.TextField(null=True)),
                ('iuphar_link', models.TextField(null=True)),
                ('iuphar_index', models.CharField(max_length=50, null=True)),
                ('has_ligand_interactions', models.BooleanField(default=False)),
                ('num_annotated_ligands', models.IntegerField(default=0)),
                ('num_interactions', models.IntegerField(default=0)),
                ('arrestin_extra_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='structure.StructureExtraProteins')),
            ],
            options={
                'db_table': 'table_gpcr_structure_browser',
            },
        ),
        migrations.AddIndex(
            model_name='gpcrstructurebrowsertable',
            index=models.Index(fields=['has_ligand_interactions'], name='gsbt_has_li_idx'),
        ),
    ]
