# Generated by Django 2.2.17 on 2026-09-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_provider', '0002_gpcrstructurebrowsertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpcrstructurebrowsertable',
            name='auxiliary_molecule_function',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gpcrstructurebrowsertable',
            name='auxiliary_molecule_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gpcrstructurebrowsertable',
            name='auxiliary_molecules',
            field=models.TextField(null=True),
        ),
    ]
