# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('date', models.DateField()),
                ('html', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
