# Generated by Django 2.0.8 on 2019-03-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('structure', '0010_auto_20190307_1242'),
        ('angles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidueAngle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField()),
                ('b_angle', models.FloatField()),
                ('hse', models.IntegerField(default=0)),
                ('sasa', models.FloatField(default=0)),
                ('phi', models.FloatField(default=0)),
                ('psi', models.FloatField(default=0)),
                ('theta', models.FloatField(default=0)),
                ('tau', models.FloatField(default=0)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'residue_angles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='angle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='angle',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='angle',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Angle',
        ),
        migrations.AlterUniqueTogether(
            name='residueangle',
            unique_together={('residue', 'structure')},
        ),
    ]
