# Generated by Django 2.0.8 on 2019-03-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0002_auto_20190314_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residueangle',
            old_name='angle',
            new_name='a_angle',
        ),
    ]
