# Generated by Django 2.0.8 on 2019-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0003_auto_20190315_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residueangle',
            name='phi',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='psi',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='tau',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='theta',
            field=models.FloatField(default=0, null=True),
        ),
    ]
