# Generated by Django 2.0.8 on 2019-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0004_auto_20190315_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='rsa',
            field=models.FloatField(default=0),
        ),
    ]
