# Generated by Django 2.0.8 on 2019-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0005_residueangle_rsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='outer_angle',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='a_angle',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='b_angle',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='hse',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='rsa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residueangle',
            name='sasa',
            field=models.FloatField(default=0, null=True),
        ),
    ]
