# Generated by Django 2.0.8 on 2019-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0007_residueangle_core_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='ss_dssp',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='ss_stride',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
