# Generated by Django 2.0.8 on 2019-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0009_auto_20190819_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='tau_angle',
            field=models.FloatField(default=0, null=True),
        ),
    ]
