# Generated by Django 2.0.8 on 2020-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0010_residueangle_tau_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='chi1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='chi2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='chi3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='chi4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='chi5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='residueangle',
            name='missing_atoms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
