# Generated by Django 2.0.8 on 2020-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0011_auto_20200402_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='residueangle',
            name='rotation_angle',
            field=models.FloatField(default=0, null=True),
        ),
    ]
