# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignprotBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_similarity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('seq_identity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('paralog_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
            ],
            options={
                'db_table': 'gprotein_barcode',
            },
        ),
        migrations.CreateModel(
            name='SignprotStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDB_code', models.CharField(max_length=4)),
                ('resolution', models.DecimalField(decimal_places=3, max_digits=5)),
                ('origin', models.ManyToManyField(to='protein.Protein')),
            ],
            options={
                'db_table': 'signprot_structure',
            },
        ),
    ]
