# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20161027_1105'),
        ('residue', '0001_initial'),
        ('signprot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignprotBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_similarity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('seq_identity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('paralog_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('CGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
                ('Gprotein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'gprotein_barcode',
            },
        ),
    ]
