# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0002_signprotbarcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signprotbarcode',
            old_name='Gprotein',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='signprotbarcode',
            old_name='CGN',
            new_name='residue',
        ),
    ]
