# Generated by Django 2.0.4 on 2018-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0003_signprotcomplex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signprotcomplex',
            old_name='chain',
            new_name='alpha',
        ),
        migrations.AddField(
            model_name='signprotcomplex',
            name='beta',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signprotcomplex',
            name='gamma',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
