# Generated by Django 2.0.4 on 2018-08-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20180809_1551'),
        ('signprot', '0004_auto_20180801_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signprotcomplex',
            old_name='beta',
            new_name='beta_chain',
        ),
        migrations.RenameField(
            model_name='signprotcomplex',
            old_name='gamma',
            new_name='gamma_chain',
        ),
        migrations.AddField(
            model_name='signprotcomplex',
            name='beta_protein',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='beta_protein', to='protein.Protein'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signprotcomplex',
            name='gamma_protein',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gamma_protein', to='protein.Protein'),
            preserve_default=False,
        ),
    ]
