# Generated by Django 2.0.4 on 2019-07-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
        ('signprot', '0006_auto_20190702_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signprotstructure',
            name='origin',
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='protein',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
            preserve_default=False,
        ),
    ]
