# Generated by Django 3.0.3 on 2020-08-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citation_page_name'),
        ('structure', '0028_auto_20200829_1704'),
        ('protein', '0009_auto_20200511_1818'),
        ('signprot', '0007_auto_20190711_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signprotstructure',
            name='PDB_code',
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='pdb_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='publication_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='stabilizing_agents',
            field=models.ManyToManyField(to='structure.StructureStabilizingAgent'),
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='structure_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='structure.StructureType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SignprotStructureExtraProteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=50, null=True)),
                ('chain', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=20)),
                ('wt_coverage', models.IntegerField(null=True)),
                ('protein_conformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signprot.SignprotStructure')),
                ('wt_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'signprot_extra_proteins',
            },
        ),
        migrations.AddField(
            model_name='signprotstructure',
            name='extra_proteins',
            field=models.ManyToManyField(related_name='extra_proteins', to='signprot.SignprotStructureExtraProteins'),
        ),
    ]
