# Generated by Django 3.0.3 on 2020-10-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0008_auto_20200829_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signprotstructure',
            name='extra_proteins',
        ),
    ]
