# Generated by Django 3.0.3 on 2021-02-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_auto_20201126_1704'),
        ('signprot', '0010_auto_20201021_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='signprotstructure',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
    ]
