# Generated by Django 2.2.1 on 2022-02-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0011_signprotstructure_pdb_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignprotInteractions',
        ),
    ]
