# Generated by Django 2.2.17 on 2026-09-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0013_signprotcomplex_alpha_backbone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signprotcomplex',
            name='alpha',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='signprotcomplex',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
    ]
