# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_type', models.CharField(max_length=10)),
                ('assay_description', models.TextField(max_length=1000)),
                ('pchembl_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('published_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('published_relation', models.CharField(max_length=10)),
                ('published_type', models.CharField(max_length=20)),
                ('published_units', models.CharField(max_length=20)),
                ('standard_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('standard_relation', models.CharField(max_length=10)),
                ('standard_type', models.CharField(max_length=20)),
                ('standard_units', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChemblAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.CharField(max_length=50, unique=True)),
                ('web_links', models.ManyToManyField(to='common.WebLink')),
            ],
            options={
                'db_table': 'chembl_assays',
            },
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('canonical', models.NullBooleanField()),
                ('ambigious_alias', models.NullBooleanField()),
            ],
            options={
                'db_table': 'ligand',
            },
        ),
        migrations.CreateModel(
            name='LigandProperities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField(null=True)),
                ('inchikey', models.CharField(max_length=50, null=True, unique=True)),
                ('mw', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('rotatable_bonds', models.SmallIntegerField(null=True)),
                ('hacc', models.SmallIntegerField(null=True)),
                ('hdon', models.SmallIntegerField(null=True)),
                ('logp', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ligand_properities',
            },
        ),
        migrations.CreateModel(
            name='LigandRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ligand_role',
            },
        ),
        migrations.CreateModel(
            name='LigandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ligand_type',
            },
        ),
        migrations.CreateModel(
            name='LigandVendorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('vendor_external_id', models.CharField(max_length=300)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='ligand.LigandProperities')),
            ],
        ),
        migrations.CreateModel(
            name='LigandVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandVendors'),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='ligand_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandType'),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='web_links',
            field=models.ManyToManyField(to='common.WebLink'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='properities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandProperities'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
    ]
