# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170602_1642'),
        ('protein', '0003_auto_20161027_1105'),
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_type', models.CharField(max_length=10)),
                ('assay_description', models.TextField(max_length=1000)),
                ('pchembl_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('published_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('published_relation', models.CharField(max_length=10)),
                ('published_type', models.CharField(max_length=20)),
                ('published_units', models.CharField(max_length=20)),
                ('standard_value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('standard_relation', models.CharField(max_length=10)),
                ('standard_type', models.CharField(max_length=20)),
                ('standard_units', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChemblAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.CharField(max_length=50, unique=True)),
                ('web_links', models.ManyToManyField(to='common.WebLink')),
            ],
            options={
                'db_table': 'chembl_assays',
            },
        ),
        migrations.CreateModel(
            name='LigandVendorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('vendor_external_id', models.CharField(max_length=300)),
                ('sid', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigandVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='hacc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='hdon',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='logp',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='mw',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='rotatable_bonds',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='lp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandProperities'),
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandVendors'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set([('ligand', 'protein', 'assay')]),
        ),
    ]
