# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AlterUniqueTogether(
            name='ligand',
            unique_together=set([('name', 'canonical')]),
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set([('ligand', 'protein', 'assay')]),
        ),
    ]
