# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AlterUniqueTogether(
            name='ligand',
            unique_together={('name', 'canonical')},
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together={('ligand', 'protein', 'assay')},
        ),
    ]
