
# Generated by Django 3.0.4 on 2020-03-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0007_proteingproteinpair_references'),
        ('ligand', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasedExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_author', models.CharField(max_length=50)),
                ('chembl', models.CharField(max_length=40, null=True)),
                ('residue', models.CharField(max_length=5, null=True)),
                ('mutation', models.CharField(max_length=5, null=True)),
                ('endogenous_ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endogenous_ligand_bias', to='ligand.Ligand')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='BiasedPathways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_author', models.CharField(max_length=50)),
                ('chembl', models.CharField(max_length=40, null=True)),
                ('relevance', models.CharField(max_length=50, null=True)),
                ('signalling_protein', models.CharField(max_length=20, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalling_protein', models.CharField(max_length=60)),
                ('family', models.CharField(max_length=60, null=True)),
                ('cell_line', models.CharField(max_length=60, null=True)),
                ('assay_type', models.CharField(max_length=60, null=True)),
                ('assay_measure', models.CharField(max_length=60, null=True)),
                ('assay_time_resolved', models.CharField(max_length=60, null=True)),
                ('ligand_function', models.CharField(max_length=60, null=True)),
                ('quantitive_measure_type', models.CharField(max_length=60, null=True)),
                ('quantitive_activity', models.FloatField(max_length=60, null=True)),
                ('quantitive_activity_sign', models.CharField(max_length=3, null=True)),
                ('quantitive_unit', models.CharField(max_length=60, null=True)),
                ('qualitative_activity', models.CharField(max_length=60, null=True)),
                ('quantitive_efficacy', models.FloatField(max_length=60, null=True)),
                ('efficacy_measure_type', models.CharField(max_length=60, null=True)),
                ('efficacy_sign', models.CharField(max_length=3, null=True)),
                ('efficacy_unit', models.CharField(max_length=60, null=True)),
                ('bias_reference', models.CharField(max_length=60, null=True)),
                ('bias_value', models.FloatField(max_length=60, null=True)),
                ('bias_value_initial', models.FloatField(max_length=60, null=True)),
                ('biased_experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_data', to='ligand.BiasedExperiment')),
                ('emax_ligand_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAssayAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_data_authors', to='ligand.ExperimentAssay')),
            ],
        ),
        migrations.CreateModel(
            name='BiasedPathwaysAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_outcome_high', models.CharField(max_length=200)),
                ('pathway_outcome_summary', models.CharField(max_length=200, null=True)),
                ('pathway_outcome_detail', models.CharField(max_length=200, null=True)),
                ('experiment_pathway_distinction', models.CharField(max_length=200, null=True)),
                ('experiment_system', models.CharField(max_length=40, null=True)),
                ('experiment_outcome_method', models.CharField(max_length=200, null=True)),
                ('biased_pathway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biased_pathway', to='ligand.BiasedPathways')),
            ],
        ),
        migrations.CreateModel(
            name='BiasedExperimentVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_data_vendors', to='ligand.BiasedExperiment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_LigandVendorLink', to='ligand.LigandVendorLink')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('chembl', models.CharField(max_length=60, null=True)),
                ('vendor_quantity', models.CharField(max_length=5)),
                ('article_quantity', models.CharField(max_length=5)),
                ('labs_quantity', models.CharField(max_length=5)),
                ('residue', models.CharField(max_length=5, null=True)),
                ('mutation', models.CharField(max_length=5, null=True)),
                ('primary', models.CharField(max_length=40, null=True)),
                ('secondary', models.CharField(max_length=40, null=True)),
                ('endogenous_ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endogenous_ligand_bias_analyzed', to='ligand.Ligand')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
                ('reference_ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_ligand_bias_analyzed', to='ligand.Ligand')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=60, null=True)),
                ('order_no', models.IntegerField(null=True)),
                ('signalling_protein', models.CharField(max_length=60)),
                ('cell_line', models.CharField(max_length=60, null=True)),
                ('assay_type', models.CharField(max_length=60, null=True)),
                ('assay_measure', models.CharField(max_length=60, null=True)),
                ('assay_time_resolved', models.CharField(max_length=60, null=True)),
                ('ligand_function', models.CharField(max_length=60, null=True)),
                ('quantitive_measure_type', models.CharField(max_length=60, null=True)),
                ('quantitive_activity_initial', models.FloatField(max_length=60, null=True)),
                ('quantitive_activity', models.FloatField(max_length=60, null=True)),
                ('quantitive_activity_sign', models.CharField(max_length=3, null=True)),
                ('quantitive_unit', models.CharField(max_length=60, null=True)),
                ('qualitative_activity', models.CharField(max_length=60, null=True)),
                ('quantitive_efficacy', models.FloatField(max_length=60, null=True)),
                ('efficacy_measure_type', models.CharField(max_length=60, null=True)),
                ('efficacy_sign', models.CharField(max_length=3, null=True)),
                ('efficacy_unit', models.CharField(max_length=60, null=True)),
                ('potency', models.CharField(max_length=60, null=True)),
                ('t_coefficient', models.CharField(max_length=60, null=True)),
                ('t_value', models.CharField(max_length=60, null=True)),
                ('log_bias_factor', models.CharField(max_length=60, null=True)),
                ('t_factor', models.CharField(max_length=60, null=True)),
                ('assay_description', models.CharField(max_length=900, null=True)),
                ('emax_ligand_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_data', to='ligand.AnalyzedExperiment')),
            ],
        ),
    ]
