# Generated by Django 2.0.13 on 2019-03-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_proteingproteinpair_g_protein_subunit'),
        ('mutation', '0002_auto_20180117_1457'),
        ('common', '0001_initial'),
        ('ligand', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=20)),
                ('assay_type', models.CharField(max_length=20)),
                ('measurng_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BiasedExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_author', models.CharField(max_length=50)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ligand.Ligand')),
                ('mutation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mutation.Mutation')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='protein.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalling_protein', models.CharField(max_length=50)),
                ('assay_type', models.CharField(max_length=30, null=True)),
                ('assay_measure', models.CharField(max_length=30)),
                ('ligand_function', models.CharField(max_length=30)),
                ('quantitive_measure_type', models.CharField(max_length=10, null=True)),
                ('quantitive_activity', models.FloatField(max_length=10, null=True)),
                ('quantitive_activity_sign', models.CharField(choices=[('gt', 'greater_than'), ('lt', 'less_than'), ('eq', 'equal'), ('ap', 'approximately')], max_length=3, null=True)),
                ('quantitive_unit', models.CharField(max_length=10, null=True)),
                ('qualitative_activity', models.CharField(max_length=10, null=True)),
                ('quantitive_efficacy', models.FloatField(max_length=10)),
                ('efficacy_measure_type', models.CharField(max_length=30)),
                ('efficacy_sign', models.CharField(choices=[('gt', 'greater_than'), ('lt', 'less_than'), ('eq', 'equal'), ('ap', 'approximately')], max_length=3)),
                ('efficacy_unit', models.CharField(max_length=10)),
                ('bias_measure_type', models.CharField(max_length=50)),
                ('bias_pathway_relationship', models.CharField(max_length=50)),
                ('bias_quantitive_activity', models.CharField(max_length=50)),
                ('bias_ligand_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand')),
                ('biased_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.BiasedExperiment')),
                ('ligand_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ExperimentAssay.efficacy_ligand_reference+', to='ligand.Ligand')),
            ],
        ),
    ]
