# Generated by Django 2.0.4 on 2019-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='endogenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ligandproperities',
            name='sequence',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
