# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0002_auto_20170829_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandvendorlink',
            name='lp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='ligand.LigandProperities'),
        ),
    ]
