# Generated by Django 2.0.13 on 2019-03-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('ligand', '0003_annotationassay_biasedexperiment_experimentassay'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residue.Residue'),
        ),
    ]
