# Generated by Django 3.0.2 on 2020-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0003_analyzedassay_analyzedexperiment_biasedexperiment_biasedexperimentvendors_biasedpathways_biasedpathw'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedexperiment',
            name='mutation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='residue',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
