# Generated by Django 3.0.2 on 2020-01-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0004_auto_20200122_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='mutation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='residue',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
