# Generated by Django 2.0.13 on 2019-03-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0004_biasedexperiment_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentassay',
            name='bias_ligand_reference',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='bias_measure_type',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='bias_pathway_relationship',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='bias_quantitive_activity',
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='bias_ligand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='bias_measure_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='bias_pathway_relationship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='bias_quantitive_activity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
