# Generated by Django 3.0.8 on 2020-08-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
        ('common', '0001_initial'),
        ('ligand', '0004_auto_20200122_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='cell_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='mutation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='residue',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_description',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_measure',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='cell_line',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='efficacy_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='efficacy_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='ligand_function',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='log_bias_factor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='potency',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='qualitative_activity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_activity',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_activity_initial',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='signalling_protein',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_coefficient',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_factor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_value',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='chembl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='source',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay'),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='pchembl_value',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_relation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_units',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_value',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_reference',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_value',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_value_initial',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='ligand_function',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_activity',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ChemblAssays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl', models.CharField(max_length=100, null=True)),
                ('smiles', models.TextField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('standard_type', models.CharField(max_length=100, null=True)),
                ('standard_value', models.CharField(max_length=100, null=True)),
                ('standard_units', models.CharField(max_length=100, null=True)),
                ('standard_relation', models.CharField(max_length=100, null=True)),
                ('assay_description', models.CharField(max_length=1000, null=True)),
                ('assay_type', models.CharField(max_length=50, null=True)),
                ('pchembl_value', models.CharField(max_length=50, null=True)),
                ('document_chembl_id', models.CharField(max_length=50, null=True)),
                ('cell_line', models.TextField(null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
    ]
