# Generated by Django 3.0.8 on 2020-08-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0009_auto_20200511_1818'),
        ('ligand', '0004_auto_20200604_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='cell_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay'),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='pchembl_value',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_relation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_units',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_value',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ChemblAssays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl', models.CharField(max_length=100, null=True)),
                ('smiles', models.TextField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('standard_type', models.CharField(max_length=100, null=True)),
                ('standard_value', models.CharField(max_length=100, null=True)),
                ('standard_units', models.CharField(max_length=100, null=True)),
                ('standard_relation', models.CharField(max_length=100, null=True)),
                ('assay_description', models.CharField(max_length=1000, null=True)),
                ('assay_type', models.CharField(max_length=50, null=True)),
                ('pchembl_value', models.CharField(max_length=50, null=True)),
                ('document_chembl_id', models.CharField(max_length=50, null=True)),
                ('cell_line', models.TextField(null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
    ]
