# Generated by Django 3.0.2 on 2020-01-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0003_auto_20191121_1616'),
        ('ligand', '0005_auto_20200122_0246'),
    ]

    operations = [
    ]
