# Generated by Django 3.0.8 on 2020-08-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0005_auto_20200826_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChemblAssays',
        ),
    ]
