# Generated by Django 3.0.2 on 2020-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0005_auto_20200122_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_description',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_measure',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='assay_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='cell_line',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='efficacy_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='efficacy_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='ligand_function',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='log_bias_factor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='potency',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='qualitative_activity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_activity',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_activity_initial',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='quantitive_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='signalling_protein',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_coefficient',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_factor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_value',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='chembl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='source',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_reference',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_value',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_value_initial',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='ligand_function',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_activity',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_measure_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_unit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=60),
        ),
    ]
