# Generated by Django 2.0.13 on 2019-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0005_auto_20190314_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='bias_qualitative_activity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
