# Generated by Django 3.0.3 on 2020-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0006_delete_chemblassays'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='pdbe',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
