# Generated by Django 3.0.3 on 2020-02-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0006_auto_20200203_1049'),
        ('ligand', '0006_merge_20200124_1831'),
    ]

    operations = [
    ]
