# Generated by Django 3.0.2 on 2020-04-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0006_auto_20200203_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedexperiment',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
