# Generated by Django 2.0.13 on 2019-03-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0006_biasedexperiment_bias_qualitative_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_ligand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand'),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='mutation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mutation.Mutation'),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='ligand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.efficacy_ligand_reference+', to='ligand.Ligand'),
        ),
    ]
