# Generated by Django 3.0.3 on 2020-10-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_auto_20200831_1835'),
        ('ligand', '0007_ligand_pdbe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandPeptideStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=20)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'ligand_peptide_structure',
            },
        ),
    ]
