# Generated by Django 3.0.2 on 2020-05-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
        ('ligand', '0007_auto_20200429_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemblAssays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=50, null=True)),
                ('chembl', models.CharField(max_length=50, null=True)),
                ('smiles', models.CharField(max_length=250, null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('standard_type', models.CharField(max_length=50, null=True)),
                ('standard_value', models.CharField(max_length=50, null=True)),
                ('standard_units', models.CharField(max_length=50, null=True)),
                ('standard_relation', models.CharField(max_length=50, null=True)),
                ('assay_description', models.CharField(max_length=50, null=True)),
                ('assay_type', models.CharField(max_length=50, null=True)),
                ('pchembl_value', models.CharField(max_length=50, null=True)),
                ('document_chembl_id', models.CharField(max_length=50, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
    ]
