# Generated by Django 2.0.13 on 2019-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0007_auto_20190318_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
