# Generated by Django 3.0.8 on 2020-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0007_ligandreceptorstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedexperiment',
            name='lignad_pubchem',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='lignad_pubchem',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='biasedpathways',
            name='lignad_pubchem',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
