# Generated by Django 3.0.8 on 2020-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0008_auto_20200924_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedexperiment',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='lignad_pubchem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
