# Generated by Django 3.1.6 on 2021-02-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_auto_20201116_1501'),
        ('ligand', '0008_ligandpeptidestructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='residue',
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='auxiliary_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_auxiliary_protein', to='protein.protein'),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='auxiliary_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_protein', to='protein.protein'),
        ),
        migrations.AddField(
            model_name='biasedpathways',
            name='lignad_pubchem',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
