# Generated by Django 2.0.13 on 2019-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0008_experimentassay_cell_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
