# Generated by Django 3.0.2 on 2020-05-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ligand', '0008_chemblassays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblassays',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
            preserve_default=False,
        ),
    ]
