# Generated by Django 2.0.13 on 2019-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0009_auto_20190318_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_measure_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_sign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='efficacy_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='ligand_function',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
