# Generated by Django 3.0.2 on 2020-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0009_auto_20200511_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblassays',
            name='assay_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chemblassays',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemblassays',
            name='standard_relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemblassays',
            name='standard_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemblassays',
            name='standard_units',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemblassays',
            name='standard_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
