# Generated by Django 3.1.6 on 2021-02-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_auto_20201116_1501'),
        ('ligand', '0009_auto_20210215_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandReceptorStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3, null=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_protein', to='protein.protein')),
                ('reference_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_protein', to='protein.protein')),
            ],
        ),
    ]
