# Generated by Django 3.0.8 on 2020-10-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200511_1818'),
        ('common', '0001_initial'),
        ('ligand', '0009_auto_20200924_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayExperiment_dublicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_type', models.CharField(max_length=10)),
                ('assay_description', models.TextField(max_length=1000)),
                ('pchembl_value', models.CharField(max_length=10, null=True)),
                ('published_value', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('published_relation', models.CharField(max_length=10, null=True)),
                ('published_type', models.CharField(max_length=20, null=True)),
                ('published_units', models.CharField(max_length=20, null=True)),
                ('standard_value', models.CharField(max_length=10, null=True)),
                ('standard_relation', models.CharField(max_length=10)),
                ('standard_type', models.CharField(max_length=20)),
                ('standard_units', models.CharField(max_length=20)),
                ('chembl', models.CharField(max_length=100, null=True)),
                ('smiles', models.TextField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('document_chembl_id', models.CharField(max_length=50, null=True)),
                ('cell_line', models.TextField(null=True)),
                ('assay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
            ],
        ),
    ]
