# Generated by Django 3.1.6 on 2021-05-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0010_ligandreceptorstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biasedpathways',
            old_name='lignad_pubchem',
            new_name='ligand_pubchem',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='assay_measure',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='effector_family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_a',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_b',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_c',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_d',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_effector',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='ligand_source_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='ligand_source_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='ligand_source_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='ligand_source_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
    ]
