# Generated by Django 3.0.2 on 2020-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0010_auto_20200511_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblassays',
            name='smiles',
            field=models.CharField(max_length=550, null=True),
        ),
    ]
