# Generated by Django 2.0.13 on 2019-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0010_auto_20190318_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_measure_type',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_pathway_relationship',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_qualitative_activity',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_quantitive_activity',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='submission_author',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=70),
        ),
    ]
