# Generated by Django 2.0.13 on 2019-04-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0011_auto_20190327_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_measure_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_pathway_relationship',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_qualitative_activity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='bias_quantitive_activity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='submission_author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='biased_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_data', to='ligand.BiasedExperiment'),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=50),
        ),
    ]
