# Generated by Django 3.1.6 on 2021-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0011_auto_20210510_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentassay',
            name='effector_family',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
