# Generated by Django 3.0.2 on 2020-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0011_auto_20200511_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblassays',
            name='smiles',
            field=models.TextField(null=True),
        ),
    ]
