# Generated by Django 3.0.8 on 2020-10-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0011_auto_20201028_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='smiles',
        ),
    ]
