# Generated by Django 3.1.6 on 2021-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0011_auto_20210216_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedexperiment',
            name='ligand_source_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='ligand_source_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='ligand_source_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='ligand_source_type',
            field=models.TextField(null=True),
        ),
    ]
