# Generated by Django 3.1.6 on 2021-07-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0012_auto_20210308_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biasedpathways',
            name='ligand_pubchem',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='assay_measure',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='reference_protein',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='effector_family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_a',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_b',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_c',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_d',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_e',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_effector',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_assay_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_ExperimentAssay.bias_ligand_reference_assay+', to='ligand.experimentassay'),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_ligand_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='external_ligand_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='auxiliary_protein',
            field=models.TextField(null=True),
        ),
    ]
