# Generated by Django 3.1.6 on 2021-05-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0012_experimentassay_effector_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biasedpathways',
            name='ligand_pubchem',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='effector_family',
        ),
    ]
