# Generated by Django 3.0.8 on 2020-11-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0012_auto_20201029_0747'),
        ('ligand', '0008_ligandpeptidestructure'),
    ]

    operations = [
    ]
