# Generated by Django 3.0.2 on 2020-05-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ligand', '0012_auto_20200526_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblassays',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
    ]
