# Generated by Django 2.2.1 on 2022-02-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('protein', '0016_auto_20220225_1650'),
        ('ligand', '0012_auto_20210308_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedLigands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pathway', models.CharField(max_length=60, null=True)),
                ('second_pathway', models.CharField(max_length=60, null=True)),
                ('delta_logEmaxEC50', models.FloatField(max_length=60, null=True)),
                ('delta_logTauKA', models.FloatField(max_length=60, null=True)),
                ('subtype_balanced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BiasedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=60, null=True)),
                ('endogenous_status', models.CharField(max_length=60, null=True)),
                ('receptor_isoform', models.CharField(max_length=60, null=True)),
                ('active_receptor_complex', models.CharField(max_length=60, null=True)),
                ('cell_line', models.CharField(max_length=60, null=True)),
                ('tissue', models.CharField(max_length=60, null=True)),
                ('species', models.CharField(max_length=60, null=True)),
                ('primary_effector_family', models.CharField(max_length=60, null=True)),
                ('primary_effector_subtype', models.CharField(max_length=60, null=True)),
                ('molecule_1', models.CharField(max_length=60, null=True)),
                ('molecule_2', models.CharField(max_length=60, null=True)),
                ('measured_process', models.CharField(max_length=60, null=True)),
                ('pathway_level', models.CharField(max_length=60, null=True)),
                ('assay_type', models.CharField(max_length=60, null=True)),
                ('EC50', models.FloatField(max_length=60, null=True)),
                ('EC50_sign', models.CharField(max_length=60, null=True)),
                ('qualitative_activity', models.CharField(max_length=60, null=True)),
                ('Emax', models.FloatField(max_length=60, null=True)),
                ('Emax_sign', models.CharField(max_length=60, null=True)),
                ('Tau_KA', models.FloatField(max_length=60, null=True)),
                ('delta_Tau_KA', models.FloatField(max_length=60, null=True)),
                ('time_resolved', models.CharField(max_length=60, null=True)),
                ('pathway_preferred', models.CharField(max_length=60, null=True)),
                ('subtype_biased', models.CharField(max_length=60, null=True)),
                ('physiology_biased', models.CharField(max_length=60, null=True)),
                ('pathway_biased', models.CharField(max_length=60, null=True)),
                ('pathway_subtype_biased', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endogenous_GTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endogenous_status', models.CharField(max_length=200, null=True)),
                ('potency_ranking', models.FloatField(max_length=60, null=True)),
                ('pec50', models.CharField(max_length=200, null=True)),
                ('pKi', models.CharField(max_length=200, null=True)),
                ('pic50', models.CharField(max_length=200, null=True)),
                ('pKd', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigandID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LigandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='auxiliary_protein',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='endogenous_ligand',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='reference_ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='auxiliary_protein',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='endogenous_ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentvendors',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentvendors',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='chemblassay',
            name='web_links',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='biased_experiment',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='emax_ligand_reference',
        ),
        migrations.RemoveField(
            model_name='experimentassayauthors',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='ligandproperities',
            name='ligand_type',
        ),
        migrations.RemoveField(
            model_name='ligandproperities',
            name='web_links',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='reference_protein',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='assay',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='cell_line',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_relation',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_type',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_units',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='published_value',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='smiles',
        ),
        migrations.RemoveField(
            model_name='biasedpathways',
            name='ligand_pubchem',
        ),
        migrations.RemoveField(
            model_name='ligandvendorlink',
            name='lp',
        ),
        migrations.RemoveField(
            model_name='ligandvendorlink',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='ligandvendorlink',
            name='vendor_external_id',
        ),
        migrations.AddField(
            model_name='ligand',
            name='ambiguous_alias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ligand',
            name='clean_inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='hacc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='hdon',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='inchikey',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='ligand_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandType'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='logp',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='mw',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='rotatable_bonds',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='sequence',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='uniprot',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='external_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='ligand.Ligand'),
        ),
        migrations.AlterField(
            model_name='ligandvendorlink',
            name='url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='ligand',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='AnalyzedAssay',
        ),
        migrations.DeleteModel(
            name='AnalyzedExperiment',
        ),
        migrations.DeleteModel(
            name='BiasedExperiment',
        ),
        migrations.DeleteModel(
            name='BiasedExperimentVendors',
        ),
        migrations.DeleteModel(
            name='ChemblAssay',
        ),
        migrations.DeleteModel(
            name='ExperimentAssay',
        ),
        migrations.DeleteModel(
            name='ExperimentAssayAuthors',
        ),
        migrations.DeleteModel(
            name='LigandReceptorStatistics',
        ),
        migrations.AddField(
            model_name='ligandimage',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='ligandid',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='ligandid',
            name='web_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebResource'),
        ),
        migrations.AddField(
            model_name='endogenous_gtp',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='endogenous_gtp',
            name='ligand_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole'),
        ),
        migrations.AddField(
            model_name='endogenous_gtp',
            name='ligand_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Species'),
        ),
        migrations.AddField(
            model_name='endogenous_gtp',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
        migrations.AddField(
            model_name='endogenous_gtp',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='biaseddata',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='biaseddata',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='biaseddata',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='balancedligands',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='balancedligands',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='balancedligands',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='ambigious_alias',
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='endogenous',
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='properities',
        ),
        migrations.DeleteModel(
            name='LigandProperities',
        ),
    ]
