# Generated by Django 3.1.6 on 2021-07-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0012_auto_20210308_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubchem_id', models.TextField(null=True)),
                ('default_name', models.TextField(null=True)),
                ('smiles', models.TextField(null=True)),
                ('inchikey', models.TextField(null=True)),
                ('sequence', models.TextField(null=True)),
                ('pdb', models.TextField(null=True)),
                ('old_ligand_id', models.IntegerField(null=True)),
                ('ligand_type', models.CharField(choices=[('1', 'small molecule'), ('2', 'protein'), ('3', 'peptide'), ('4', 'N/A'), ('5', None), ('6', 'ion'), ('7', 'constitutive')], default='small-molecule', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='biasedpathways',
            name='ligand_pubchem',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='assay_measure',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='reference_protein',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='effector_family',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_a',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_b',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_c',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_d',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_e',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='measured_effector',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_ligand_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='external_ligand_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='measured_biological_process',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biasedexperiment',
            name='auxiliary_protein',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('resource', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('specialty', models.CharField(choices=[('1', 'ligand'), ('2', 'vendor')], default='1', max_length=6)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand_v2')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand_v2_Physchem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mw', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('rotatable_bonds', models.SmallIntegerField(null=True)),
                ('hacc', models.SmallIntegerField(null=True)),
                ('hdon', models.SmallIntegerField(null=True)),
                ('logp', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand_v2')),
            ],
        ),
    ]
