# Generated by Django 3.1.6 on 2021-07-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20210727_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedassay',
            name='reference_ligand_id',
        ),
    ]
