# Generated by Django 3.1.6 on 2021-05-04 12:32

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20210504_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentassay',
            name='signal_detection_tecnique',
            field=models.TextField(null=True),
        ),
    ]
