# Generated by Django 3.0.2 on 2020-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20200527_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemblassays',
            name='cell_line',
            field=models.TextField(null=True),
        ),
    ]
