# Generated by Django 2.2.1 on 2022-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20220208_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligand',
            name='pubchem_id',
        ),
        migrations.RemoveField(
            model_name='ligandvendorlink',
            name='vendor_external_id',
        ),
        migrations.AddField(
            model_name='ligandvendorlink',
            name='external_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='ambiguous_alias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='uniprot',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ligandvendorlink',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
