# Generated by Django 3.1.6 on 2021-07-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20210708_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_assay_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_ExperimentAssay.bias_ligand_reference_assay+', to='ligand.experimentassay'),
        ),
    ]
