# Generated by Django 3.0.8 on 2020-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_merge_20201106_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AssayExperiment_dublicate',
        ),
    ]
