# Generated by Django 2.0.13 on 2019-05-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20190425_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='potency_ratio',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
