# Generated by Django 3.1.6 on 2021-07-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citation_page_name'),
        ('protein', '0012_auto_20210226_1300'),
        ('ligand', '0013_auto_20210708_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTP_endogenous_ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_type', models.TextField(null=True)),
                ('endogenous_princip', models.TextField(null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
