# Generated by Django 3.1.6 on 2021-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0013_auto_20210515_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_ligand_id',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
