# Generated by Django 2.2.1 on 2022-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_auto_20220301_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
