# Generated by Django 3.1.6 on 2021-07-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_analyzedassay_reference_assay_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligand_v2_physchem',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='synonyms',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='reference_assay_initial',
        ),
        migrations.DeleteModel(
            name='Ligand_v2',
        ),
        migrations.DeleteModel(
            name='Ligand_v2_Physchem',
        ),
        migrations.DeleteModel(
            name='Synonyms',
        ),
    ]
