# Generated by Django 3.1.6 on 2021-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_analyzedassay_reference_ligand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='external_ligand_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
