# Generated by Django 3.1.6 on 2021-05-05 10:28

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_experimentassay_signal_detection_tecnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentassay',
            name='effector_family',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
