# Generated by Django 3.0.8 on 2020-07-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('ligand', '0014_chemblassays_cell_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='cell_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='chembl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ChemblAssay'),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_relation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_units',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_value',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
