# Generated by Django 3.0.8 on 2020-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_auto_20201111_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_relation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_units',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
