# Generated by Django 3.1.6 on 2021-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0014_remove_analyzedassay_reference_ligand_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentAssay',
            new_name='BiasedExperimentAssay',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='reference_ligand_id',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
