# Generated by Django 3.1.7 on 2021-11-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('protein', '0015_proteincouplings_physiological_ligand'),
        ('ligand', '0015_auto_20210727_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endogenous_GTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endogenous_status', models.CharField(max_length=200, null=True)),
                ('potency_ranking', models.CharField(max_length=200, null=True)),
                ('pec50', models.CharField(max_length=200, null=True)),
                ('pKi', models.CharField(max_length=200, null=True)),
                ('pic50', models.CharField(max_length=200, null=True)),
                ('pKd', models.CharField(max_length=200, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('ligand_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandrole')),
                ('ligand_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.species')),
                ('publication', models.ManyToManyField(null=True, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
        migrations.CreateModel(
            name='BiasedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=60, null=True)),
                ('endogenous_status', models.CharField(max_length=60, null=True)),
                ('receptor_isoform', models.CharField(max_length=60, null=True)),
                ('active_receptor_complex', models.CharField(max_length=60, null=True)),
                ('cell_line', models.CharField(max_length=60, null=True)),
                ('tissue', models.CharField(max_length=60, null=True)),
                ('specie', models.CharField(max_length=60, null=True)),
                ('primary_effector_family', models.CharField(max_length=60, null=True)),
                ('primary_effector_subtype', models.CharField(max_length=60)),
                ('molecule_1', models.CharField(max_length=60, null=True)),
                ('molecule_2', models.CharField(max_length=60, null=True)),
                ('pathway_level', models.CharField(max_length=60, null=True)),
                ('assay_type', models.CharField(max_length=60, null=True)),
                ('EC50', models.FloatField(max_length=60, null=True)),
                ('EC50_sign', models.CharField(max_length=60, null=True)),
                ('qualitative_activity', models.CharField(max_length=60, null=True)),
                ('Emax', models.FloatField(max_length=60, null=True)),
                ('Emax_sign', models.CharField(max_length=60, null=True)),
                ('Tau_KA', models.FloatField(max_length=60, null=True)),
                ('delta_Tau_KA', models.FloatField(max_length=60, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
