# Generated by Django 2.0.13 on 2019-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0015_auto_20190506_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='doi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
