# Generated by Django 3.1.6 on 2021-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0015_analyzedassay_external_ligand_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedassay',
            name='external_ligand_ids',
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='external_ligand_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
