# Generated by Django 3.0.8 on 2020-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0015_auto_20201117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay_description',
            field=models.TextField(max_length=1500),
        ),
    ]
