# Generated by Django 3.1.6 on 2021-07-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citation_page_name'),
        ('ligand', '0015_auto_20210720_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtp_endogenous_ligand',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.publication'),
        ),
    ]
