# Generated by Django 3.1.7 on 2022-05-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('protein', '0016_auto_20220225_1650'),
        ('ligand', '0015_auto_20220430_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_type', models.CharField(max_length=10)),
                ('assay_description', models.TextField(max_length=1000)),
                ('activity_value', models.CharField(max_length=10, null=True)),
                ('activity_ranges', models.CharField(max_length=10, null=True)),
                ('standard_relation', models.CharField(max_length=10)),
                ('value_type', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('document_chembl_id', models.CharField(max_length=50, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
                ('publication', models.ManyToManyField(to='common.Publication')),
            ],
        ),
    ]
