# Generated by Django 3.1.6 on 2021-07-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0012_auto_20210226_1300'),
        ('common', '0005_auto_20210725_1110'),
        ('ligand', '0015_auto_20210727_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTP_endogenous_ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_type', models.TextField(null=True)),
                ('endogenous_princip', models.TextField(null=True)),
                ('pec50_avg', models.FloatField(max_length=60, null=True)),
                ('pec50_min', models.FloatField(max_length=60, null=True)),
                ('pec50_max', models.FloatField(max_length=60, null=True)),
                ('pKi_avg', models.FloatField(max_length=60, null=True)),
                ('pKi_min', models.FloatField(max_length=60, null=True)),
                ('pKi_max', models.FloatField(max_length=60, null=True)),
                ('gpt_link', models.TextField(null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('publication', models.ManyToManyField(null=True, to='common.Publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
