# Generated by Django 2.2.1 on 2022-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('ligand', '0015_auto_20220430_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayexperiment',
            name='pchembl_value',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_type',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_units',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_value',
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='p_activity_ranges',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='p_activity_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='standard_activity_value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='value_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
