# Generated by Django 3.0.8 on 2020-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0015_auto_20200716_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='pchembl_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
