# Generated by Django 2.0.13 on 2019-05-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_biasedexperiment_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='doi',
        ),
    ]
