# Generated by Django 2.2.1 on 2022-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_auto_20220614_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedpathwaysassay',
            name='pathway_outcome_detail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='biasedpathwaysassay',
            name='pathway_outcome_summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
