# Generated by Django 3.1.6 on 2021-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_auto_20210517_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='log_bias_factor_e',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
