# Generated by Django 3.0.8 on 2020-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_auto_20201117_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandproperities',
            name='sequence',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
