# Generated by Django 3.1.7 on 2021-11-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0015_proteincouplings_physiological_ligand'),
        ('ligand', '0016_biaseddata_endogenous_gtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endogenous_gtp',
            name='ligand_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandrole'),
        ),
        migrations.AlterField(
            model_name='endogenous_gtp',
            name='ligand_specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.species'),
        ),
    ]
