# Generated by Django 3.1.6 on 2021-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_gtp_endogenous_ligand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biasedexperimentassay',
            old_name='bias_value',
            new_name='relative_transduction_coef',
        ),
        migrations.RenameField(
            model_name='biasedexperimentassay',
            old_name='bias_value_initial',
            new_name='transduction_coef',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='log_bias_factor_a',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='log_bias_factor_b',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='log_bias_factor_c',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='log_bias_factor_d',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='log_bias_factor_e',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='t_coefficient',
        ),
        migrations.RemoveField(
            model_name='analyzedassay',
            name='t_value',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='delta_emax_ec50',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='delta_relative_transduction_coef',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='relative_transduction_coef',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='transduction_coef',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='potency',
            field=models.FloatField(max_length=60, null=True),
        ),
    ]
