# Generated by Django 3.1.6 on 2021-07-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_analyzedassay_reference_assay_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedassay',
            name='reference_assay_initial',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='test_ExperimentAssay.bias_ligand_reference_assay+', to='ligand.experimentassay'),
            preserve_default=False,
        ),
    ]
