# Generated by Django 3.0.8 on 2020-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0016_auto_20200717_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
