# Generated by Django 3.1.7 on 2021-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20211116_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaseddata',
            name='primary_effector_subtype',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
