# Generated by Django 3.0.8 on 2020-07-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20200717_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assayexperiment',
            unique_together=set(),
        ),
    ]
