# Generated by Django 2.0.13 on 2019-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_remove_biasedexperiment_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biasedexperiment',
            old_name='bias_pathway_relationship',
            new_name='bias_assay',
        ),
        migrations.RenameField(
            model_name='biasedexperiment',
            old_name='bias_measure_type',
            new_name='bias_value',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_ligand_reference',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_qualitative_activity',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_quantitive_activity',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='ligand_reference',
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
