# Generated by Django 3.1.6 on 2021-09-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20210816_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedexperiment',
            name='receptor_gtpo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='receptor_isoform',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biasedexperimentassay',
            name='pathway_level',
            field=models.TextField(null=True),
        ),
    ]
