# Generated by Django 2.2.1 on 2022-07-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20220726_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedpathways',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
    ]
