# Generated by Django 3.1.6 on 2021-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20210512_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentassay',
            name='effector_family',
        ),
        migrations.RemoveField(
            model_name='experimentassay',
            name='measured_effector',
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
