# Generated by Django 3.0.8 on 2020-11-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20201126_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='published_value',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
