# Generated by Django 3.1.7 on 2022-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0017_auto_20220524_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentaldata',
            name='assay_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
