# Generated by Django 2.0.13 on 2019-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20190531_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='potency_ratio',
        ),
    ]
