# Generated by Django 3.1.7 on 2021-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20211117_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endogenous_gtp',
            name='potency_ranking',
            field=models.FloatField(max_length=60, null=True),
        ),
    ]
