# Generated by Django 3.1.6 on 2021-06-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20210610_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='ligandreceptorstatistics',
            name='reference_protein',
        ),
    ]
