# Generated by Django 3.1.6 on 2021-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20210512_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='molecule_2',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
