# Generated by Django 3.1.6 on 2021-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20210903_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='secondary',
        ),
        migrations.AddField(
            model_name='analyzedassay',
            name='pathway_level',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='receptor_gtpo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='receptor_isoform',
            field=models.TextField(null=True),
        ),
    ]
