# Generated by Django 3.0.8 on 2020-11-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200511_1818'),
        ('ligand', '0018_auto_20201127_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligandreceptorstatistics',
            old_name='potency',
            new_name='value',
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='reference_protein',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reference_protein', to='protein.Protein'),
            preserve_default=False,
        ),
    ]
