# Generated by Django 2.2.1 on 2022-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0018_auto_20220726_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedpathways',
            name='signalling_protein',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
