# Generated by Django 3.1.6 on 2021-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0019_auto_20210621_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='primary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligandreceptorstatistics',
            name='secondary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
