# Generated by Django 3.1.7 on 2022-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('ligand', '0019_auto_20220525_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assayexperiment',
            old_name='pchembl_value',
            new_name='p_activity_value',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_type',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_units',
        ),
        migrations.RemoveField(
            model_name='assayexperiment',
            name='standard_value',
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='p_activity_ranges',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='source',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='standard_activity_value',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='value_type',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='assay_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assayexperiment',
            name='document_chembl_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ExperimentalData',
        ),
    ]
