# Generated by Django 3.1.7 on 2022-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0019_auto_20220525_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentaldata',
            name='assay_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentaldata',
            name='p_activity_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experimentaldata',
            name='standard_relation',
            field=models.CharField(max_length=100),
        ),
    ]
