# Generated by Django 3.1.6 on 2021-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0019_auto_20210906_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biasedexperimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
