# Generated by Django 3.1.7 on 2022-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0019_auto_20220726_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='assayexperiment',
            name='affinity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='count_affinity_test',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='count_potency_test',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='potency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
