# Generated by Django 3.1.7 on 2022-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0020_auto_20220923_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasedpathways',
            name='effect_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biasedpathways',
            name='relevance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
