# Generated by Django 3.1.6 on 2021-06-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citation_page_name'),
        ('ligand', '0020_auto_20210623_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubchem_id', models.TextField(null=True)),
                ('default_name', models.TextField(null=True)),
                ('smiles', models.TextField(null=True)),
                ('inchikey', models.TextField(null=True)),
                ('pdb', models.TextField(null=True)),
                ('ligand_type', models.CharField(choices=[('1', 'small molecule'), ('2', 'protein'), ('3', 'peptide'), ('4', 'N/A'), ('5', None), ('6', 'ion'), ('7', 'constitutive')], default='small-molecule', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('specialty', models.CharField(choices=[('1', 'ligand'), ('2', 'vendor')], default='1', max_length=6)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand_v2')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.webresource')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand_v2_Physchem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mw', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('rotatable_bonds', models.SmallIntegerField(null=True)),
                ('hacc', models.SmallIntegerField(null=True)),
                ('hdon', models.SmallIntegerField(null=True)),
                ('logp', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand_v2')),
            ],
        ),
    ]
