# Generated by Django 3.1.7 on 2021-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0020_biaseddata_measured_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='time_resolved',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
