# Generated by Django 3.1.7 on 2022-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0020_auto_20220527_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentaldata',
            name='assay_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='experimentaldata',
            name='standard_activity_value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experimentaldata',
            name='standard_relation',
            field=models.CharField(max_length=10),
        ),
    ]
