# Generated by Django 3.1.6 on 2021-09-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0020_auto_20210914_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedassay',
            name='signalling_protein',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
