# Generated by Django 3.1.7 on 2022-01-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210725_1110'),
        ('ligand', '0021_biaseddata_time_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField(null=True)),
                ('inchikey', models.CharField(max_length=50, null=True, unique=True)),
                ('sequence', models.CharField(max_length=1000, null=True)),
                ('mw', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('rotatable_bonds', models.SmallIntegerField(null=True)),
                ('hacc', models.SmallIntegerField(null=True)),
                ('hdon', models.SmallIntegerField(null=True)),
                ('logp', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('ligand_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandtype')),
                ('web_links', models.ManyToManyField(to='common.WebLink')),
            ],
            options={
                'db_table': 'ligand_properties',
            },
        ),
    ]
