# Generated by Django 2.0.13 on 2019-05-31 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0021_auto_20190531_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_assay',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_ligand_reference',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='bias_value',
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='bias_assay',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='bias_ligand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='experimentassay',
            name='bias_value',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='cell_line',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='qualitative_activity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='quantitive_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=30),
        ),
    ]
