# Generated by Django 3.1.6 on 2021-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0021_ligand_v2_ligand_v2_physchem_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand_v2',
            name='old_ligand_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ligand_v2',
            name='sequence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='resource',
            field=models.TextField(null=True),
        ),
    ]
