# Generated by Django 3.0.8 on 2021-01-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0021_auto_20201229_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='lignad_pubchem',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='chembl',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='lignad_pubchem',
        ),
    ]
