# Generated by Django 2.0.13 on 2019-05-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0022_auto_20190531_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentassay',
            name='bias_assay',
        ),
    ]
