# Generated by Django 3.1.7 on 2022-01-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0022_ligandproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLigand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pdbe', models.CharField(max_length=3, null=True)),
                ('canonical', models.NullBooleanField()),
                ('ambiguous_alias', models.NullBooleanField()),
                ('endogenous', models.BooleanField(default=False)),
                ('properities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandproperties')),
            ],
        ),
    ]
