# Generated by Django 2.2.1 on 2023-03-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0022_assayexperiment_reference_ligand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandpeptidestructure',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
    ]
