# Generated by Django 3.1.7 on 2023-02-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0042_auto_20220916_1514'),
        ('ligand', '0022_assayexperiment_reference_ligand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandpeptidestructure',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
