# Generated by Django 3.1.7 on 2022-01-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0023_testligand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testligand',
            old_name='properities',
            new_name='properties',
        ),
    ]
