# Generated by Django 2.0.13 on 2019-05-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0023_remove_experimentassay_bias_assay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_measure',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_time_resolved',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='assay_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='ligand_function',
            field=models.CharField(max_length=53, null=True),
        ),
        migrations.AlterField(
            model_name='experimentassay',
            name='signalling_protein',
            field=models.CharField(max_length=40),
        ),
    ]
