# Generated by Django 3.1.7 on 2023-02-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0043_auto_20230210_1010'),
        ('ligand', '0023_auto_20230210_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandpeptidestructure',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structuremodel'),
        ),
    ]
