# Generated by Django 3.0.3 on 2023-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0042_auto_20220916_1514'),
        ('ligand', '0023_auto_20230310_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandpeptidestructure',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel'),
        ),
    ]
