# Generated by Django 2.2.1 on 2022-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0024_auto_20220119_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandproperties',
            name='clean_inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='ligandproperties',
            name='inchikey',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
    ]
