# Generated by Django 2.0.13 on 2019-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0024_auto_20190531_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_reference',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
