# Generated by Django 3.0.3 on 2023-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0024_ligandpeptidestructure_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligandvendorlink',
            name='external_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
