# Generated by Django 2.2.17 on 2024-07-16 17:17

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    replaces = [('ligand', '0026_auto_20240609_1631_squashed_0028_auto_20240609_1954'), ('ligand', '0027_auto_20240630_0600')]

    dependencies = [
        ('ligand', '0025_auto_20230831_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandMol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', django_rdkit.models.fields.MolField()),
                ('ligand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
            ],
        ),
        migrations.AddIndex(
            model_name='ligandmol',
            index=django.contrib.postgres.indexes.GistIndex(fields=['molecule'], name='ligand_liga_molecul_c5aed2_gist'),
        ),
        migrations.CreateModel(
            name='LigandFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfp2', django_rdkit.models.fields.BfpField(null=True)),
                ('ligand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
            ],
        ),
        migrations.AddIndex(
            model_name='ligandfingerprint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='ligand_liga_mfp2_5c80ac_gist'),
        ),
    ]
