# Generated by Django 3.0.8 on 2021-01-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200511_1818'),
        ('ligand', '0025_auto_20210118_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='residue',
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='auxiliary_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_auxiliary_protein', to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='biasedexperiment',
            name='auxiliary_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_protein', to='protein.Protein'),
        ),
    ]
