# Generated by Django 2.0.13 on 2019-06-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0025_auto_20190531_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentassay',
            name='bias_value_initial',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
