# Generated by Django 3.1.7 on 2022-01-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0025_auto_20220121_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='pathway_biased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biaseddata',
            name='physiology_biased',
            field=models.BooleanField(default=False),
        ),
    ]
