# Generated by Django 3.1.7 on 2022-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0026_auto_20220128_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='subtype_biased',
            field=models.BooleanField(default=False),
        ),
    ]
