# Generated by Django 2.0.13 on 2019-06-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0026_experimentassay_bias_value_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLigand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
            ],
        ),
        migrations.RenameField(
            model_name='experimentassay',
            old_name='bias_ligand_reference',
            new_name='emax_ligand_reference',
        ),
    ]
