# Generated by Django 2.2.17 on 2024-06-30 04:00

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0026_auto_20240609_1631_squashed_0028_auto_20240609_1954'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ligandfingerprint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mfp2'], name='ligand_liga_mfp2_5c80ac_gist'),
        ),
    ]
