# Generated by Django 3.1.7 on 2022-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0027_biaseddata_subtype_biased'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='pathway_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
