# Generated by Django 2.2.17 on 2025-08-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
        ('protein', '0020_auto_20250318_1242'),
        ('ligand', '0027_auto_20241204_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='qualitative_activity',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='helm',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='source',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ligandrole',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='clean_inchikey',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ligandid',
            unique_together={('ligand', 'index', 'web_resource')},
        ),
        migrations.CreateModel(
            name='LigandTargetPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandEffect')),
                ('ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandType')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='ligandrole',
            name='effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandEffect'),
        ),
    ]
