# Generated by Django 2.0.13 on 2019-06-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0027_auto_20190621_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceligand',
            name='assay_measure',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='assay_time_resolved',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='assay_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='bias_reference',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='cell_line',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='efficacy_measure_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='efficacy_sign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='efficacy_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='emax_ligand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExperimentAssay.bias_ligand_reference+', to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='ligand_function',
            field=models.CharField(max_length=53, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='qualitative_activity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='quantitive_activity',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='quantitive_activity_sign',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='quantitive_efficacy',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='quantitive_measure_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='quantitive_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referenceligand',
            name='signalling_protein',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
