# Generated by Django 2.2.17 on 2025-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0028_auto_20250826_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayexperiment',
            name='standard_relation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
