# Generated by Django 3.1.7 on 2022-02-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0029_auto_20220201_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biaseddata',
            name='pathway_preferred',
        ),
    ]
