# Generated by Django 2.2.17 on 2025-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0029_auto_20250829_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='gpcrdb_id',
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
    ]
