# Generated by Django 2.0.13 on 2019-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0029_auto_20190621_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='family',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
