# Generated by Django 2.0.13 on 2019-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0030_analyzedassay_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedassay',
            name='order_no',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
