# Generated by Django 3.1.7 on 2022-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0030_remove_biaseddata_pathway_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='pathway_preferred',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
