# Generated by Django 2.2.17 on 2026-05-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0030_ligand_gpcrdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
                ('assay_type', models.CharField(max_length=20)),
                ('parameter_class', models.CharField(max_length=40)),
                ('modality', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ligand_assay_classification',
            },
        ),
        migrations.AddField(
            model_name='ligand',
            name='radioactive',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assayexperiment',
            name='assay_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.AssayClassification'),
        ),
    ]
