# Generated by Django 2.0.13 on 2019-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0031_auto_20190621_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='submission_name',
        ),
    ]
