# Generated by Django 3.1.7 on 2022-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0031_biaseddata_pathway_preferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaseddata',
            name='pathway_biased',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='biaseddata',
            name='physiology_biased',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='biaseddata',
            name='subtype_biased',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
