# Generated by Django 2.2.17 on 2026-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0031_auto_20260512_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='stereo_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
