# Generated by Django 3.1.7 on 2022-02-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0032_auto_20220201_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='auxiliary_protein',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='endogenous_ligand',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='analyzedexperiment',
            name='reference_ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='endogenous_ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='biasedexperiment',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentassay',
            name='biased_experiment',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentassay',
            name='emax_ligand_reference',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentvendors',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='biasedexperimentvendors',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='experimentassayauthors',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='AnalyzedAssay',
        ),
        migrations.DeleteModel(
            name='AnalyzedExperiment',
        ),
        migrations.DeleteModel(
            name='BiasedExperiment',
        ),
        migrations.DeleteModel(
            name='BiasedExperimentAssay',
        ),
        migrations.DeleteModel(
            name='BiasedExperimentVendors',
        ),
        migrations.DeleteModel(
            name='ExperimentAssayAuthors',
        ),
    ]
