# Generated by Django 2.0.13 on 2019-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0032_remove_analyzedexperiment_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedassay',
            name='t_factor',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
