# Generated by Django 2.0.13 on 2019-06-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0033_analyzedassay_t_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzedassay',
            old_name='bias',
            new_name='potency',
        ),
    ]
