# Generated by Django 2.0.13 on 2019-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0034_auto_20190624_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentassay',
            name='bias_reference',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
