# Generated by Django 3.1.7 on 2022-02-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0015_proteincouplings_physiological_ligand'),
        ('common', '0005_auto_20210725_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedLigands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pathway', models.CharField(max_length=60, null=True)),
                ('second_pathway', models.CharField(max_length=60, null=True)),
                ('delta_logEmaxEC50', models.FloatField(max_length=60, null=True)),
                ('delta_logTauKA', models.FloatField(max_length=60, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.publication')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
