# Generated by Django 3.1.7 on 2022-02-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0033_auto_20220203_1630'),
        ('ligand', '0036_balancedligands'),
    ]

    operations = [
    ]
