# Generated by Django 2.0.13 on 2019-06-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0036_auto_20190625_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedassay',
            name='log_bias_factor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_coefficient',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_factor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedassay',
            name='t_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
