# Generated by Django 3.1.7 on 2022-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0037_merge_20220215_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedligands',
            name='subtype_balanced',
            field=models.BooleanField(default=False),
        ),
    ]
