# Generated by Django 3.1.7 on 2022-02-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0038_balancedligands_subtype_balanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaseddata',
            name='pathway_subtype_biased',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
