# Generated by Django 2.0.13 on 2019-07-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutation', '0002_auto_20180117_1457'),
        ('residue', '0002_auto_20180504_1417'),
        ('ligand', '0038_auto_20190626_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedexperiment',
            name='mutation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mutation.Mutation'),
        ),
        migrations.AddField(
            model_name='analyzedexperiment',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
    ]
