# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('reference', models.TextField(null=True)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='PublicationJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'publication_journal',
            },
        ),
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('html', models.TextField()),
            ],
            options={
                'ordering': ('-date',),
                'db_table': 'release_notes',
            },
        ),
        migrations.CreateModel(
            name='ReleaseStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ReleaseNotes')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'release_statistics',
            },
        ),
        migrations.CreateModel(
            name='ReleaseStatisticsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'release_statistics_type',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
            ],
            options={
                'db_table': 'web_link',
            },
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'web_resource',
            },
        ),
        migrations.AddField(
            model_name='weblink',
            name='web_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.WebResource'),
        ),
        migrations.AddField(
            model_name='releasestatistics',
            name='statistics_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ReleaseStatisticsType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.PublicationJournal'),
        ),
        migrations.AddField(
            model_name='publication',
            name='web_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink'),
        ),
        migrations.AlterUniqueTogether(
            name='weblink',
            unique_together=set([('web_resource', 'index')]),
        ),
    ]
