# Generated by Django 3.0.3 on 2020-08-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('video', models.TextField(null=True)),
                ('docs', models.TextField(null=True)),
                ('main', models.BooleanField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Publication')),
            ],
            options={
                'db_table': 'citation',
            },
        ),
    ]
