# Generated by Django 3.0.3 on 2020-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='page_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
