# Generated by Django 2.2.17 on 2025-08-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('common', '0007_auto_20250825_1349'), ('common', '0008_defaultcitation'), ('common', '0009_auto_20250825_1525'), ('common', '0010_auto_20250825_1531'), ('common', '0011_auto_20250825_1553')]

    dependencies = [
        ('common', '0006_releasestatistics_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='publication',
        ),
        migrations.AddField(
            model_name='citation',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='DefaultCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(default=None, unique=True)),
                ('publication', models.ManyToManyField(default=None, to='common.Publication')),
            ],
            options={
                'db_table': 'default_citation',
            },
        ),
    ]
