# Generated by Django 2.2.17 on 2025-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='publication',
        ),
        migrations.AddField(
            model_name='citation',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
    ]
