# Generated by Django 2.2.17 on 2025-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20250825_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(null=True)),
                ('publication', models.ManyToManyField(to='common.Publication')),
            ],
            options={
                'db_table': 'default_citation',
            },
        ),
    ]
