# Generated by Django 2.2.17 on 2025-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_citation_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcitation',
            name='main',
            field=models.TextField(unique=True),
        ),
    ]
