# Generated by Django 2.2.17 on 2025-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_defaultcitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcitation',
            name='publication',
            field=models.ManyToManyField(default=None, null=True, to='common.Publication'),
        ),
    ]
