# Generated by Django 2.2.17 on 2025-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20250825_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='defaultcitation',
            name='publication',
            field=models.ManyToManyField(default=None, to='common.Publication'),
        ),
    ]
