# Generated by Django 2.2.17 on 2025-08-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20250825_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcitation',
            name='main',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
