# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0003_rotamer_missing_atoms'),
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResiduePairInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VDW', 'Van der Waals'), ('HYD', 'Hydrophobic'), ('AEE', 'Aromatic edge-to-edge'), ('AFF', 'Aromatic face-to-face'), ('AEF', 'Aromatic edge-to-face'), ('AFE', 'Aromatic face-to-edge'), ('APC', 'Aromatic pi-cation'), ('ACP', 'Aromatic cation-pi')], max_length=3)),
                ('referenced_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
                ('residues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
            ],
            options={
                'db_table': 'interaction_residue_pair',
            },
        ),
    ]
