# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('residue', '0001_initial'),
        ('structure', '0003_rotamer_missing_atoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractingResiduePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contactnetwork.interactingresiduepair_set+', to='contenttypes.ContentType')),
                ('referenced_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
                ('res1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue1', to='residue.Residue')),
                ('res2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue2', to='residue.Residue')),
            ],
            options={
                'db_table': 'interacting_residue_pair',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
        migrations.CreateModel(
            name='AromaticInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_aromatic',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='HydrophobicInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_hydrophobic',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='PolarInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
                ('is_charged_res1', models.BooleanField()),
                ('is_charged_res2', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_polar',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='VanDerWaalsInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_van_der_waals',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contactnetwork.interaction_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='FaceToEdgeInteraction',
            fields=[
                ('aromaticinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.AromaticInteraction')),
                ('res1_has_face', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_aromatic_face_edge',
            },
            bases=('contactnetwork.aromaticinteraction',),
        ),
        migrations.CreateModel(
            name='FaceToFaceInteraction',
            fields=[
                ('aromaticinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.AromaticInteraction')),
            ],
            options={
                'db_table': 'interaction_aromatic_face_face',
            },
            bases=('contactnetwork.aromaticinteraction',),
        ),
        migrations.CreateModel(
            name='PiCationInteraction',
            fields=[
                ('aromaticinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.AromaticInteraction')),
                ('res1_has_pi', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_aromatic_pi_cation',
            },
            bases=('contactnetwork.aromaticinteraction',),
        ),
        migrations.CreateModel(
            name='PolarBackboneSidechainInteraction',
            fields=[
                ('polarinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.PolarInteraction')),
                ('res1_is_sidechain', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_polar_backbone_sidechain',
            },
            bases=('contactnetwork.polarinteraction',),
        ),
        migrations.CreateModel(
            name='PolarSidechainSidechainInteraction',
            fields=[
                ('polarinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.PolarInteraction')),
            ],
            options={
                'db_table': 'interaction_polar_sidechain_sidechain',
            },
            bases=('contactnetwork.polarinteraction',),
        ),
    ]
