# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractingResiduePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contactnetwork.interactingresiduepair_set+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'interacting_residue_pair',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
        migrations.CreateModel(
            name='AromaticInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_aromatic',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='HydrophobicInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_hydrophobic',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='PolarInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
                ('is_charged_res1', models.BooleanField()),
                ('is_charged_res2', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_polar',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.CreateModel(
            name='VanDerWaalsInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contactnetwork.Interaction')),
            ],
            options={
                'db_table': 'interaction_van_der_waals',
            },
            bases=('contactnetwork.interaction',),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contactnetwork.interaction_set+', to='contenttypes.ContentType'),
        ),
    ]
