# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_structure_interactions'),
        ('residue', '0001_initial'),
        ('contactnetwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceToEdgeInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res1_has_face', models.BooleanField()),
            ],
            options={
                'db_table': 'interaction_aromatic_face_edge',
            },
        ),
        migrations.CreateModel(
            name='FaceToFaceInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interaction_aromatic_face_face',
            },
        ),
        migrations.CreateModel(
            name='HydrophobicInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interaction_hydrophobic',
            },
        ),
        migrations.CreateModel(
            name='InteractingResiduePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
                ('res1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue1', to='residue.Residue')),
                ('res2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue2', to='residue.Residue')),
            ],
            options={
                'db_table': 'interacting_residue_pair',
            },
        ),
        migrations.CreateModel(
            name='PiCationInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res1_has_pi', models.BooleanField()),
                ('interacting_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair')),
            ],
            options={
                'db_table': 'interaction_aromatic_pi_cation',
            },
        ),
        migrations.CreateModel(
            name='PolarBackboneSidechainInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_charged_res1', models.BooleanField()),
                ('is_charged_res2', models.BooleanField()),
                ('res1_is_sidechain', models.BooleanField()),
                ('interacting_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair')),
            ],
            options={
                'db_table': 'interaction_polar_backbone_sidechain',
            },
        ),
        migrations.CreateModel(
            name='PolarSidechainSidechainInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_charged_res1', models.BooleanField()),
                ('is_charged_res2', models.BooleanField()),
                ('interacting_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair')),
            ],
            options={
                'db_table': 'interaction_polar_sidechain_sidechain',
            },
        ),
        migrations.CreateModel(
            name='VanDerWaalsInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacting_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair')),
            ],
            options={
                'db_table': 'interaction_van_der_waals',
            },
        ),
        migrations.RemoveField(
            model_name='residuepairinteraction',
            name='referenced_structure',
        ),
        migrations.RemoveField(
            model_name='residuepairinteraction',
            name='residues',
        ),
        migrations.DeleteModel(
            name='ResiduePairInteraction',
        ),
        migrations.AddField(
            model_name='hydrophobicinteraction',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
        migrations.AddField(
            model_name='facetofaceinteraction',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
        migrations.AddField(
            model_name='facetoedgeinteraction',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
    ]
