# Generated by Django 2.0.8 on 2019-01-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
            ],
            options={
                'db_table': 'distance',
            },
        ),
        migrations.RemoveField(
            model_name='aromaticinteraction',
            name='interaction_ptr',
        ),
        migrations.RemoveField(
            model_name='facetoedgeinteraction',
            name='aromaticinteraction_ptr',
        ),
        migrations.RemoveField(
            model_name='facetofaceinteraction',
            name='aromaticinteraction_ptr',
        ),
        migrations.RemoveField(
            model_name='hydrophobicinteraction',
            name='interaction_ptr',
        ),
        migrations.RemoveField(
            model_name='picationinteraction',
            name='aromaticinteraction_ptr',
        ),
        migrations.RemoveField(
            model_name='polarbackbonesidechaininteraction',
            name='polarinteraction_ptr',
        ),
        migrations.RemoveField(
            model_name='polarinteraction',
            name='interaction_ptr',
        ),
        migrations.RemoveField(
            model_name='polarsidechainsidechaininteraction',
            name='polarinteraction_ptr',
        ),
        migrations.RemoveField(
            model_name='vanderwaalsinteraction',
            name='interaction_ptr',
        ),
        migrations.RemoveField(
            model_name='interactingresiduepair',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='specific_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AromaticInteraction',
        ),
        migrations.DeleteModel(
            name='FaceToEdgeInteraction',
        ),
        migrations.DeleteModel(
            name='FaceToFaceInteraction',
        ),
        migrations.DeleteModel(
            name='HydrophobicInteraction',
        ),
        migrations.DeleteModel(
            name='PiCationInteraction',
        ),
        migrations.DeleteModel(
            name='PolarBackboneSidechainInteraction',
        ),
        migrations.DeleteModel(
            name='PolarInteraction',
        ),
        migrations.DeleteModel(
            name='PolarSidechainSidechainInteraction',
        ),
        migrations.DeleteModel(
            name='VanDerWaalsInteraction',
        ),
        migrations.AddField(
            model_name='distance',
            name='interacting_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactnetwork.InteractingResiduePair'),
        ),
    ]
