# Generated by Django 2.0.8 on 2019-01-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_structure_stats_text'),
        ('residue', '0002_auto_20180504_1417'),
        ('contactnetwork', '0003_auto_20190115_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='interacting_pair',
        ),
        migrations.AddField(
            model_name='distance',
            name='gn1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='gn2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='res1',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_residue1', to='residue.Residue'),
        ),
        migrations.AddField(
            model_name='distance',
            name='res2',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_residue2', to='residue.Residue'),
        ),
        migrations.AddField(
            model_name='distance',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='structure.Structure'),
        ),
    ]
