# Generated by Django 2.0.8 on 2019-01-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0005_auto_20190123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='res1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_residue1', to='residue.Residue'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='res2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_residue2', to='residue.Residue'),
        ),
    ]
