# Generated by Django 2.0.8 on 2019-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0006_auto_20190125_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='atomname_residue1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='atomname_residue2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_level',
            field=models.IntegerField(default=0),
        ),
    ]
