# Generated by Django 2.0.8 on 2019-06-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
        ('structure', '0017_structure_contact_representative_score'),
        ('residue', '0002_auto_20180504_1417'),
        ('contactnetwork', '0009_auto_20190605_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsensusInteractions',
            new_name='ConsensusInteraction',
        ),
    ]
