# Generated by Django 2.0.8 on 2019-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0010_auto_20190605_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensusinteraction',
            name='state_specific',
            field=models.BooleanField(default=False),
        ),
    ]
