# Generated by Django 2.0.8 on 2020-04-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0011_consensusinteraction_state_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance_cb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='distance_helix_center',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
