# Generated by Django 2.0.8 on 2020-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0012_auto_20200407_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='atomname_residue1',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='atomname_residue2',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
