# Generated by Django 3.0.3 on 2022-10-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('ligand', '0022_assayexperiment_reference_ligand'),
        ('contactnetwork', '0013_auto_20200602_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractingPeptideResiduePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide_amino_acid_three_letter', models.CharField(max_length=3)),
                ('peptide_amino_acid', models.CharField(max_length=1)),
                ('peptide_sequence_number', models.IntegerField()),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peptide', to='ligand.LigandPeptideStructure')),
                ('receptor_residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_residue', to='residue.Residue')),
            ],
            options={
                'db_table': 'interacting_peptide_residue_pair',
            },
        ),
        migrations.CreateModel(
            name='InteractionPeptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide_atom', models.CharField(max_length=10)),
                ('receptor_atom', models.CharField(max_length=10)),
                ('interaction_type', models.CharField(max_length=100)),
                ('specific_type', models.CharField(max_length=100, null=True)),
                ('interaction_level', models.IntegerField()),
                ('interacting_peptide_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='contactnetwork.InteractingPeptideResiduePair')),
            ],
            options={
                'db_table': 'interaction_peptide',
            },
        ),
    ]
