# Generated by Django 3.1.7 on 2023-02-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('contactnetwork', '0014_interactingpeptideresiduepair_interactionpeptide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactingpeptideresiduepair',
            name='receptor_residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor_residue', to='residue.residue'),
        ),
    ]
