# Generated by Django 3.1.7 on 2023-02-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('contactnetwork', '0015_auto_20230214_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactingpeptideresiduepair',
            name='receptor_residue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_residue', to='residue.residue'),
        ),
    ]
