# Generated by Django 2.2.17 on 2026-07-23 11:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0024_protein_family_classification'),
        ('structure', '0049_structuremodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('protein_count', models.PositiveSmallIntegerField(default=0)),
                ('tree_method', models.CharField(default='neighbor_joining', max_length=64)),
                ('segment_source', models.CharField(default='generic_conserved', max_length=64)),
                ('bootstrap', models.PositiveSmallIntegerField(default=0)),
                ('branch_mode', models.CharField(default='regular', max_length=32)),
                ('tree_newick', models.TextField(blank=True, default='')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('build_version', models.CharField(default='v1', max_length=32)),
                ('source_hash', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.ProteinFamily')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.ProteinFamily')),
            ],
            options={
                'db_table': 'classification_treenetwork',
            },
        ),
        migrations.CreateModel(
            name='StructureSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_normalized', models.FloatField(default=0.0)),
                ('protein_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('protein_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.ProteinState')),
                ('structure_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('structure_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
            ],
            options={
                'db_table': 'classification_structuresimilarity',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceptorSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.PositiveSmallIntegerField()),
                ('similarity', models.PositiveSmallIntegerField()),
                ('protein_ref', models.ForeignKey(db_column='ref', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_ref', to='protein.Protein')),
                ('protein_target', models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_target', to='protein.Protein')),
                ('ref_class', models.ForeignKey(blank=True, db_column='ref_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_ref_class', to='protein.ProteinFamily')),
                ('target_class', models.ForeignKey(blank=True, db_column='target_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_target_class', to='protein.ProteinFamily')),
            ],
            options={
                'db_table': 'classification_receptorsimilarity',
            },
        ),
        migrations.CreateModel(
            name='ClusterCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('sequence', 'Sequence'), ('structure_active', 'Structure (active)'), ('structure_inactive', 'Structure (inactive)')], db_index=True, max_length=32)),
                ('plot_type', models.CharField(choices=[('tsne', 't-SNE')], db_index=True, default='tsne', max_length=16)),
                ('group_key', models.CharField(db_index=True, default='global', max_length=32)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.Protein')),
            ],
            options={
                'db_table': 'classification_clustercoord',
            },
        ),
        migrations.AddIndex(
            model_name='treenetwork',
            index=models.Index(fields=['class_family', 'group_key'], name='ctn_class_group_idx'),
        ),
        migrations.AddIndex(
            model_name='treenetwork',
            index=models.Index(fields=['family', 'group_key'], name='ctn_family_group_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['state', 'protein_ref', 'protein_target'], name='css_state_prot_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['state', 'structure_ref', 'structure_target'], name='css_state_struct_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['distance'], name='css_dist_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresimilarity',
            index=models.Index(fields=['distance_normalized'], name='css_distn_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarity',
            constraint=models.UniqueConstraint(fields=('state', 'structure_ref', 'structure_target'), name='css_uniq_state_pair'),
        ),
        migrations.AddConstraint(
            model_name='structuresimilarity',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, structure_ref=django.db.models.expressions.F('structure_target')), name='css_ref_ne_target'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'identity'], name='crs_cls_id_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'similarity'], name='crs_cls_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'identity'], name='crs_cls_id_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'similarity'], name='crs_cls_sim_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.UniqueConstraint(fields=('protein_ref', 'protein_target'), name='crs_uniq_pair'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, protein_ref=django.db.models.expressions.F('protein_target')), name='crs_ref_ne_target'),
        ),
        migrations.AddIndex(
            model_name='clustercoord',
            index=models.Index(fields=['dataset_type', 'plot_type', 'group_key'], name='ccoord_ds_plot_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='clustercoord',
            index=models.Index(fields=['protein', 'dataset_type', 'group_key'], name='ccoord_prot_ds_grp_idx'),
        ),
        migrations.AddConstraint(
            model_name='clustercoord',
            constraint=models.UniqueConstraint(fields=('protein', 'dataset_type', 'plot_type', 'group_key'), name='ccoord_uniq_prot_ds_plot_grp'),
        ),
    ]
