# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentconsensus',
            name='gn_consensus',
            field=models.BinaryField(blank=True),
        ),
    ]
