# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        ('interaction', '0001_initial'),
        ('ligand', '0001_initial'),
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureligandinteraction',
            name='pdb_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
        migrations.AddField(
            model_name='structureligandinteraction',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='fragment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Fragment'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='interaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.ResidueFragmentInteractionType'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='rotamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Rotamer'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='structure_ligand_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.StructureLigandInteraction'),
        ),
        migrations.AddField(
            model_name='residuefragmentatom',
            name='interaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.ResidueFragmentInteraction'),
        ),
        migrations.AddField(
            model_name='residuefragmentatom',
            name='structureligandpair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.StructureLigandInteraction'),
        ),
        migrations.AddField(
            model_name='proteinligandinteraction',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='proteinligandinteraction',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation'),
        ),
    ]
