# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligand', '0001_initial'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureligandinteraction',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='structureligandinteraction',
            name='ligand_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole'),
        ),
    ]
