# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20160111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuefragmentinteractiontype',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
