# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20160926_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuefragmentinteractiontype',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
