# Generated by Django 2.2.1 on 2022-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_auto_20180117_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuefragmentatom',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='residuefragmentatom',
            name='structureligandpair',
        ),
        migrations.DeleteModel(
            name='ProteinLigandInteraction',
        ),
        migrations.DeleteModel(
            name='ResidueFragmentAtom',
        ),
    ]
