# Generated by Django 3.1.7 on 2023-02-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0043_auto_20230210_1010'),
        ('interaction', '0004_auto_20220225_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureligandinteraction',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
