# Generated by Django 3.0.3 on 2024-10-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_auto_20230712_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureligandinteraction',
            name='pdb_reference',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
