# Generated by Django 2.2.17 on 2026-09-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_structureligandinteraction_site_chain_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureligandinteraction',
            name='ligand_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole'),
        ),
    ]
