# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('synonym', models.CharField(max_length=300, null=True)),
                ('drugtype', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=15)),
                ('indication', models.CharField(max_length=150, null=True)),
                ('approval', models.CharField(max_length=5)),
                ('clinicalstatus', models.CharField(default=False, max_length=30, null=True)),
                ('phasedate', models.CharField(default=True, max_length=15, null=True)),
                ('phase', models.CharField(default=True, max_length=1, null=True)),
                ('moa', models.CharField(default=True, max_length=30, null=True)),
                ('targetlevel', models.CharField(default='NA', max_length=10, null=True)),
                ('externallink', models.CharField(max_length=150, null=True)),
                ('novelty', models.CharField(max_length=15)),
                ('references', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
    ]
