# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0003_auto_20160426_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('synonym', models.CharField(max_length=100, null=True)),
                ('drugtype', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=30)),
                ('indication', models.CharField(max_length=200, null=True)),
                ('approval', models.IntegerField()),
                ('externallink', models.CharField(max_length=200, null=True)),
                ('novelty', models.CharField(max_length=50)),
                ('target', models.ManyToManyField(to='protein.Protein')),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
    ]
