# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='target',
            field=models.ManyToManyField(to='protein.Protein'),
        ),
    ]
