# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='approval',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='drugtype',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='externallink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='indication',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='novelty',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='synonym',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
