# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='target',
            field=models.ManyToManyField(to='protein.Protein'),
        ),
    ]
