# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drugs_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='references',
            field=models.CharField(max_length=180),
        ),
    ]
