# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drugs_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='phase',
            field=models.CharField(default=True, max_length=5, null=True),
        ),
    ]
