# Generated by Django 2.2.17 on 2023-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
        ('drugs', '0002_drugs_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='publication',
            field=models.ManyToManyField(to='common.Publication'),
        ),
    ]
