# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drugs_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='moa',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drugs',
            name='phasedate',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
    ]
