# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20170518_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='clinicalstatus',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
