# Generated by Django 3.2.18 on 2024-02-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20240208_0929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drugs2024',
            table='drugs_new',
        ),
    ]
