# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_drugs_clinicalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='phase',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
