# Generated by Django 3.2.18 on 2024-02-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_drugs2024_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drugs',
            table='drugs',
        ),
    ]
