# Generated by Django 3.2.18 on 2024-02-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
        ('ligand', '0025_auto_20230831_1052'),
        ('drugs', '0007_alter_drugs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs2024',
            name='genetic_association',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='moa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligandrole'),
        ),
        migrations.AlterField(
            model_name='indication',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
    ]
