# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20170518_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='phase',
            field=models.CharField(default=True, max_length=1, null=True),
        ),
    ]
