# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20170531_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='targetlevel',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
