# Generated by Django 3.2.18 on 2024-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20240209_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
