# Generated by Django 3.2.18 on 2024-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_alter_indication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs2024',
            name='affected_pathway',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='approval_year',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='charge',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='complexity',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='drug_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='indication_max_phase',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='novelty_score',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='similarity_to_model',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='somatic_mutation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drugs2024',
            name='tpsa',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
