# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_drugs_targetlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='references',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
