# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_drugs_targetlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='references',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
