# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'construct_chemical',
            },
        ),
        migrations.CreateModel(
            name='ChemicalConc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('concentration_unit', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_chemical_conc',
            },
        ),
        migrations.CreateModel(
            name='ChemicalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'construct_chemical_list',
            },
        ),
        migrations.CreateModel(
            name='ChemicalListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'construct_chemical_list_name',
            },
        ),
        migrations.CreateModel(
            name='ChemicalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'construct_chemical_type',
            },
        ),
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('json', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructDeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.SmallIntegerField()),
                ('end', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'construct_deletion',
            },
        ),
        migrations.CreateModel(
            name='ConstructInsertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=20, null=True)),
                ('presence', models.TextField(max_length=20, null=True)),
                ('start', models.SmallIntegerField(null=True)),
                ('end', models.SmallIntegerField(null=True)),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_insertion',
            },
        ),
        migrations.CreateModel(
            name='ConstructInsertionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('subtype', models.TextField(max_length=50, null=True)),
                ('sequence', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_insertion_type',
            },
        ),
        migrations.CreateModel(
            name='ConstructModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.TextField(max_length=50)),
                ('position_type', models.TextField(max_length=20)),
                ('pos_start', models.SmallIntegerField()),
                ('pos_end', models.SmallIntegerField()),
                ('remark', models.TextField()),
            ],
            options={
                'db_table': 'construct_modification',
            },
        ),
        migrations.CreateModel(
            name='ConstructMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('wild_type_amino_acid', models.CharField(max_length=1)),
                ('mutated_amino_acid', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'construct_mutation',
            },
        ),
        migrations.CreateModel(
            name='ContributorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('pi_email', models.TextField(max_length=50)),
                ('pi_name', models.TextField(max_length=50)),
                ('urls', models.TextField()),
                ('date', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrystalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.DecimalField(decimal_places=3, max_digits=5)),
                ('pdb_code', models.TextField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crystallization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=1000, null=True)),
                ('protein_conc', models.FloatField()),
                ('protein_conc_unit', models.TextField(max_length=10, null=True)),
                ('temp', models.FloatField()),
                ('ph_start', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_end', models.DecimalField(decimal_places=1, max_digits=3)),
                ('chemical_lists', models.ManyToManyField(to='construct.ChemicalList')),
            ],
            options={
                'db_table': 'construct_crystallization',
            },
        ),
        migrations.CreateModel(
            name='CrystallizationLigandConc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_conc', models.FloatField(null=True)),
                ('ligand_conc_unit', models.TextField(null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('ligand_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole')),
            ],
            options={
                'db_table': 'construct_crystallization_ligand_conc',
            },
        ),
        migrations.CreateModel(
            name='CrystallizationMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'construct_crystallization_methods',
            },
        ),
        migrations.CreateModel(
            name='CrystallizationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'construct_crystallization_types',
            },
        ),
        migrations.CreateModel(
            name='ExpressionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_method', models.CharField(max_length=100)),
                ('host_cell_type', models.CharField(max_length=100)),
                ('host_cell', models.CharField(max_length=100)),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_expression_system',
            },
        ),
        migrations.CreateModel(
            name='Purification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_purification',
            },
        ),
        migrations.CreateModel(
            name='PurificationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'construct_purification_step',
            },
        ),
        migrations.CreateModel(
            name='Solubilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('chemical_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalList')),
            ],
            options={
                'db_table': 'construct_solubilization',
            },
        ),
        migrations.AddField(
            model_name='purification',
            name='steps',
            field=models.ManyToManyField(to='construct.PurificationStep'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationMethods'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationTypes'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='ligands',
            field=models.ManyToManyField(to='construct.CrystallizationLigandConc'),
        ),
    ]
