# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construct', '0001_initial'),
        ('structure', '0001_initial'),
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystalinfo',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
        migrations.AddField(
            model_name='constructinsertion',
            name='insert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ConstructInsertionType'),
        ),
        migrations.AddField(
            model_name='construct',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ContributorInfo'),
        ),
        migrations.AddField(
            model_name='construct',
            name='crystal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystalInfo'),
        ),
        migrations.AddField(
            model_name='construct',
            name='crystallization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Crystallization'),
        ),
        migrations.AddField(
            model_name='construct',
            name='deletions',
            field=models.ManyToManyField(to='construct.ConstructDeletion'),
        ),
        migrations.AddField(
            model_name='construct',
            name='expression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.ExpressionSystem'),
        ),
        migrations.AddField(
            model_name='construct',
            name='insertions',
            field=models.ManyToManyField(to='construct.ConstructInsertion'),
        ),
        migrations.AddField(
            model_name='construct',
            name='modifications',
            field=models.ManyToManyField(to='construct.ConstructModification'),
        ),
        migrations.AddField(
            model_name='construct',
            name='mutations',
            field=models.ManyToManyField(to='construct.ConstructMutation'),
        ),
        migrations.AddField(
            model_name='construct',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='construct',
            name='purification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Purification'),
        ),
        migrations.AddField(
            model_name='construct',
            name='solubilization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Solubilization'),
        ),
        migrations.AddField(
            model_name='construct',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='chemicallist',
            name='chemicals',
            field=models.ManyToManyField(to='construct.ChemicalConc'),
        ),
        migrations.AddField(
            model_name='chemicallist',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalListName'),
        ),
        migrations.AddField(
            model_name='chemicalconc',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.Chemical'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='chemical_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalType'),
        ),
        migrations.AlterUniqueTogether(
            name='chemical',
            unique_together=set([('name', 'chemical_type')]),
        ),
    ]
