# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligand', '0001_initial'),
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystallizationligandconc',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='crystallizationligandconc',
            name='ligand_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='chemical_lists',
            field=models.ManyToManyField(to='construct.ChemicalList'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationMethods'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationTypes'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='ligands',
            field=models.ManyToManyField(to='construct.CrystallizationLigandConc'),
        ),
    ]
