# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construct', '0001_initial'),
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystallizationligandconc',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='crystallizationligandconc',
            name='ligand_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='chemical_lists',
            field=models.ManyToManyField(to='construct.ChemicalList'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationMethods'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='crystal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystallizationTypes'),
        ),
        migrations.AddField(
            model_name='crystallization',
            name='ligands',
            field=models.ManyToManyField(to='construct.CrystallizationLigandConc'),
        ),
    ]
