# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construct', '0001_initial'),
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='protein_conformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation'),
        ),
        migrations.AddField(
            model_name='chemicalmodification',
            name='construct_solubilization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ConstructSolubilization'),
        ),
        migrations.AddField(
            model_name='chemicallist',
            name='chemicals',
            field=models.ManyToManyField(to='construct.ChemicalConc'),
        ),
        migrations.AddField(
            model_name='chemicalconc',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.Chemical'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='chemical_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalType'),
        ),
        migrations.AddField(
            model_name='auxprotein',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.Construct'),
        ),
        migrations.AddField(
            model_name='auxprotein',
            name='protein_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.AuxProteinType'),
        ),
    ]
