# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0002_auto_20160926_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='schematics',
            field=models.TextField(null=True),
        ),
    ]
