# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('structure', '0001_initial'),
        ('construct', '0002_auto_20180117_1457'),
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystalinfo',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
        migrations.AlterUniqueTogether(
            name='constructmutationtype',
            unique_together={('slug', 'name', 'effect')},
        ),
        migrations.AddField(
            model_name='constructmutation',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='construct.Construct'),
        ),
        migrations.AddField(
            model_name='constructmutation',
            name='effects',
            field=models.ManyToManyField(related_name='bar', to='construct.ConstructMutationType'),
        ),
        migrations.AddField(
            model_name='constructmutation',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
        migrations.AddField(
            model_name='constructmodification',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='construct.Construct'),
        ),
        migrations.AddField(
            model_name='constructinsertion',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='construct.Construct'),
        ),
        migrations.AddField(
            model_name='constructinsertion',
            name='insert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ConstructInsertionType'),
        ),
        migrations.AddField(
            model_name='constructdeletion',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='construct.Construct'),
        ),
        migrations.AddField(
            model_name='construct',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ContributorInfo'),
        ),
        migrations.AddField(
            model_name='construct',
            name='crystal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.CrystalInfo'),
        ),
        migrations.AddField(
            model_name='construct',
            name='crystallization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Crystallization'),
        ),
        migrations.AddField(
            model_name='construct',
            name='expression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.ExpressionSystem'),
        ),
        migrations.AddField(
            model_name='construct',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='construct',
            name='purification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Purification'),
        ),
        migrations.AddField(
            model_name='construct',
            name='solubilization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.Solubilization'),
        ),
        migrations.AddField(
            model_name='construct',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='chemicallist',
            name='chemicals',
            field=models.ManyToManyField(to='construct.ChemicalConc'),
        ),
        migrations.AddField(
            model_name='chemicallist',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalListName'),
        ),
        migrations.AddField(
            model_name='chemicalconc',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.Chemical'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='chemical_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct.ChemicalType'),
        ),
        migrations.AlterUniqueTogether(
            name='chemical',
            unique_together={('name', 'chemical_type')},
        ),
    ]
