# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_construct_schematics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construct',
            name='schematics',
        ),
        migrations.AddField(
            model_name='construct',
            name='_schematics',
            field=models.TextField(blank=True, db_column='schematics'),
        ),
    ]
