# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('construct', '0003_auto_20160706_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
    ]
