# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_auto_20170908_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionsystem',
            name='expression_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
