# Generated by Django 2.0.1 on 2018-04-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_auto_20180117_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construct', to='structure.Structure'),
        ),
    ]
