# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0004_auto_20161014_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construct',
            name='_schematics',
        ),
        migrations.AddField(
            model_name='construct',
            name='schematics',
            field=models.BinaryField(null=True),
        ),
    ]
