# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0005_auto_20161014_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='snakecache',
            field=models.BinaryField(null=True),
        ),
    ]
