# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0008_auto_20161025_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructmutation',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
