# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0010_constructmutation_residue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructmutation',
            name='residue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
    ]
