# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0011_auto_20170314_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructmutation',
            old_name='residue_id',
            new_name='residue',
        ),
    ]
