# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0013_auto_20170726_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructMutationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'construct_mutation_type',
            },
        ),
        migrations.AlterField(
            model_name='constructdeletion',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='construct.Construct'),
        ),
        migrations.AlterField(
            model_name='constructinsertion',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='construct.Construct'),
        ),
        migrations.AlterField(
            model_name='constructmodification',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='construct.Construct'),
        ),
        migrations.AlterField(
            model_name='constructmutation',
            name='construct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='construct.Construct'),
        ),
        migrations.AlterUniqueTogether(
            name='constructmutationtype',
            unique_together=set([('slug', 'name', 'effect')]),
        ),
        migrations.AddField(
            model_name='constructmutation',
            name='effects',
            field=models.ManyToManyField(to='construct.ConstructMutationType'),
        ),
    ]
