# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0014_auto_20170727_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructmutation',
            name='mutation_type',
        ),
    ]
