# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0015_remove_constructmutation_mutation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructmutationtype',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
