from collections import OrderedDict
from decimal import Decimal

from django.core.cache import cache

AMINO_ACIDS = OrderedDict([
    ('A', 'Ala'),
    ('C', 'Cys'),
    ('D', 'Asp'),
    ('E', 'Glu'),
    ('F', 'Phe'),
    ('G', 'Gly'),
    ('H', 'His'),
    ('I', 'Ile'),
    ('K', 'Lys'),
    ('L', 'Leu'),
    ('M', 'Met'),
    ('N', 'Asn'),
    ('P', 'Pro'),
    ('Q', 'Gln'),
    ('R', 'Arg'),
    ('S', 'Ser'),
    ('T', 'Thr'),
    ('V', 'Val'),
    ('W', 'Trp'),
    ('Y', 'Tyr'),
    ('B', 'Asx'),
    ('Z', 'Glx'),
    ('J', 'Xle'),
    ('-', 'Gap'),
    ('+', 'Tie')
])

FULL_AMINO_ACIDS = OrderedDict([
    ('A', 'Alanine'),
    ('C', 'Cysteine'),
    ('D', 'Aspartate'),
    ('E', 'Glutamate'),
    ('F', 'Phenylalanine'),
    ('G', 'Glycine'),
    ('H', 'Histidine'),
    ('I', 'Isoleucine'),
    ('K', 'Lysine'),
    ('L', 'Leucine'),
    ('M', 'Methionine'),
    ('N', 'Asparagine'),
    ('P', 'Proline'),
    ('Q', 'Glutamine'),
    ('R', 'Arginine'),
    ('S', 'Serine'),
    ('T', 'Threonine'),
    ('V', 'Valine'),
    ('W', 'Tryptophan'),
    ('Y', 'Tyrosine'),
    ('B', 'Aspartate or Asparagine'),
    ('Z', 'Glutamate or Glutamine'),
    ('J', 'Leucine or Isoleucine'),
    ('-', 'Gap'),
    ('+', 'Tie')
])


# Amino Acid Propensities
AA_PROPENSITY = {
    "A":Decimal('0'),
    "R":Decimal('0.21'),
    "N":Decimal('0.65'),
    "D":Decimal('0.69'),
    "C":Decimal('0.68'),
    "E":Decimal('0.40'),
    "Q":Decimal('0.39'),
    "G":Decimal('1.00'),
    "H":Decimal('0.61'),
    "I":Decimal('0.41'),
    "L":Decimal('0.21'),
    "K":Decimal('0.26'),
    "M":Decimal('0.24'),
    "F":Decimal('0.54'),
    "P":Decimal('3.16'),
    "S":Decimal('0.50'),
    "T":Decimal('0.66'),
    "W":Decimal('0.49'),
    "Y":Decimal('0.53'),
    "V":Decimal('0.61')
}

# Amino Acid Z-scales from Sandberg et al. J. Med. Chem. 1998
# Format = AA: [Z1, Z2, Z3, Z4, Z5]
AA_ZSCALES = {
    "A": [ 0.24, -2.32,  0.60, -0.14,  1.30],
    "C": [ 0.84, -1.67,  3.75,  0.18, -2.65],
    "D": [ 3.98,  0.93,  1.93, -2.46,  0.75],
    "E": [ 3.11,  0.26, -0.11, -3.04, -0.25],
    "F": [-4.22,  1.94,  1.06,  0.54, -0.62],
    "G": [ 2.05, -4.06,  0.36, -0.82, -0.38],
    "H": [ 2.47,  1.95,  0.26,  3.90,  0.09],
    "I": [-3.89, -1.73, -1.71, -0.84,  0.26],
    "K": [ 2.29,  0.89, -2.49,  1.49,  0.31],
    "L": [-4.28, -1.30, -1.49, -0.72,  0.84],
    "M": [-2.85, -0.22,  0.47,  1.94, -0.98],
    "N": [ 3.05,  1.62,  1.04, -1.15,  1.61],
    "P": [-1.66,  0.27,  1.84,  0.70,  2.00],
    "Q": [ 1.75,  0.50, -1.44, -1.34,  0.66],
    "R": [ 3.52,  2.50, -3.50,  1.99, -0.17],
    "S": [ 2.39, -1.07,  1.15, -1.39,  0.67],
    "T": [ 0.75, -2.18, -1.12, -1.46, -0.40],
    "V": [-2.59, -2.64, -1.54, -0.85, -0.02],
    "W": [-4.36,  3.94,  0.59,  3.44, -1.59],
    "Y": [-2.54,  2.44,  0.43,  0.04, -1.47]
}
ZSCALES = ["Z1", "Z2", "Z3", "Z4", "Z5"]

# The Octanol-Interface scale from the Wimley-White scale uis used here.
HYDROPHOBICITY = {
    "I":Decimal('-1.12'),
    "L":Decimal('-1.25'),
    "F":Decimal('-1.71'),
    "V":Decimal('-0.46'),
    "M":Decimal('-0.67'),
    "P":Decimal('0.14'),
    "W":Decimal('-2.09'),
    "H":Decimal('0.11'),
    "T":Decimal('0.25'),
    "E":Decimal('0.11'),
    "Q":Decimal('0.77'),
    "C":Decimal('-0.02'),
    "Y":Decimal('-0.71'),
    "S":Decimal('0.46'),
    "A":Decimal('0.50'),
    "N":Decimal('0.85'),
    "D":Decimal('0.43'),
    "R":Decimal('1.81'),
    "G":Decimal('1.15'),
    "K":Decimal('2.80'),
    "R+":Decimal('1.81'),
    "H+":Decimal('2.33'),
    "E-":Decimal('3.63'),
    "K+":Decimal('2.80'),
    "D-":Decimal('3.64')
    }

AMINO_ACID_GROUPS = OrderedDict([
    ('HY_any', ('A', 'C', 'F', 'I', 'L', 'M', 'P', 'V', 'W', 'Y')),
    ('HY_4-5', ('F', 'M', 'Y')),
    ('HA_any', ('A', 'I', 'L', 'M', 'V')),
    ('HA_1-2', ('A', 'V')),
    ('HA_2-3', ('I', 'L', 'V')),
    ('HA_3', ('I', 'L')),
    ('HA_3-4', ('I', 'L', 'M')),
    ('M_4', ('M',)),
    ('A_1', ('A',)),
    ('I_', ('I',)),
    ('L_', ('L',)),
    ('V_', ('V',)),
    ('HR_any', ('F', 'H', 'W', 'Y')),
    ('HR_4-5', ('F', 'H', 'Y')),
    ('HR_5', ('F', 'Y')),
    ('HR_5-6', ('F', 'W', 'Y')),
    ('W_6', ('W',)),
    ('Y_?', ('Y',)),
    ('F_', ('F',)),
    ('Hb_any', ('D', 'E', 'H', 'K', 'N', 'Q', 'R', 'S', 'T', 'Y')),
    ('Hb_2', ('S', 'T')),
    ('Hb_3', ('H', 'N')),
    ('N_', ('N',)),
    ('Q_', ('Q',)),
    ('S_', ('S',)),
    ('T_', ('T',)),
    ('Hu_2-3', ('N', 'S', 'T')),
    ('Hu_3-4', ('H', 'N', 'Q')),
    ('Ha_2-3', ('D', 'N', 'S', 'T')),
    ('Ha_3', ('D', 'N')),
    ('Ha_3-4', ('D', 'E', 'H', 'N', 'Q')),
    ('Ha_4', ('E', 'H', 'Q')),
    ('Hd_4', ('H', 'Q')),
    ('Hd_4-5', ('H', 'K', 'Q')),
    ('Hd_5-6', ('K', 'R', 'Y')),
    ('Hd_6', ('R', 'Y')),
    ('+-_any', ('D', 'E', 'H', 'K', 'R')),
    ('+-_3-4', ('D', 'E', 'H')),
    ('+-_4-5', ('E', 'H', 'K')),
    ('+_any', ('H', 'K', 'R')),
    ('H_4', ('H',)),
    ('+_4-5', ('H', 'K')),
    ('K_5', ('K',)),
    ('+_5-6', ('K', 'R')),
    ('R_6', ('R',)),
    ('-_any', ('D', 'E')),
    ('D_3', ('D',)),
    ('E_4', ('E',)),
    ('Sm_0-2', ('A', 'C', 'G', 'S')),
    ('Sm_0-1', ('A', 'G')),
    ('Sm_1-2', ('A', 'C', 'S')),
    ('aH_Hig', ('A', 'K', 'L', 'M', 'R')),
    # ('aH_Med', ('E', 'F', 'I', 'Q', 'S', 'W', 'Y')),
    # ('aH_Low', ('C', 'D', 'G', 'H', 'N', 'P', 'T', 'V')),
    ('aH_Low', ('G', 'P')),
    ('G_0', ('G',)),
    ('P_2', ('P',)),
    ('C_2', ('C',)),
    ('-', ('-'))
])

# Save time by creating a reverse lookup table
cache_name = "reverse_aa_groups"
AMINO_ACID_GROUPS_AA = cache.get(cache_name)
if AMINO_ACID_GROUPS_AA == None:
    AMINO_ACID_GROUPS_AA = OrderedDict()
    for amino_acid in AMINO_ACIDS.keys():
        AMINO_ACID_GROUPS_AA[amino_acid] = []
        for feature, members in AMINO_ACID_GROUPS.items():
            if amino_acid in members:
                AMINO_ACID_GROUPS_AA[amino_acid].append(feature)
    cache.set(cache_name, AMINO_ACID_GROUPS_AA, 3600*24*7) # cache a week


AMINO_ACID_GROUP_NAMES = OrderedDict([
    ('HY_any', 'Hydrophobic'),
    ('HY_4-5', 'Hydrophobic'),
    ('HA_any', 'Hydrophobic aliphatic'),
    ('HA_1-2', 'Hydrophobic aliphatic'),
    ('HA_2-3', 'Hydrophobic aliphatic'),
    ('HA_3', 'Hydrophobic aliphatic'),
    ('HA_3-4', 'Hydrophobic aliphatic'),
    ('M_4', 'Hydrophobic aliphatic [M]'),
    ('A_1', 'Hydrophob al / α-H prop - very high [A]'),
    ('I_', 'Hydrophobic aliphatic [I]'),
    ('L_', 'Hydrophobic aliphatic [L]'),
    ('V_', 'Hydrophobic aliphatic [V]'),
    ('HR_any', 'Hydrophobic aromatic'),
    ('HR_4-5', 'Hydrophobic aromatic'),
    ('HR_5', 'Hydrophobic aromatic'),
    ('HR_5-6', 'Hydrophobic aromatic'),
    ('W_6', 'Hydrophobic aromatic [W]'),
    ('Y_?', 'Hydropob ar / H-bonding [Y]'),
    ('F_', 'Hydrophobic aromatic [F]'),
    ('Hb_any', 'Hydrogen bonding (polar)'),
    ('Hb_2', 'Hydrogen bonding'),
    ('Hb_3', 'Hydrogen bonding'),
    ('N_', 'Hydrogen bonding [N]'),
    ('Q_', 'Hydrogen bonding [Q]'),
    ('S_', 'Hydrogen bonding [S]'),
    ('T_', 'Hydrogen bonding [T]'),
    ('Hu_2-3', 'Hydrogen bonding uncharged'),
    ('Hu_3-4', 'Hydrogen bonding uncharged'),
    ('Ha_2-3', 'Hydrogen bond acceptor'),
    ('Ha_3', 'Hydrogen bond acceptor'),
    ('Ha_3-4', 'Hydrogen bond acceptor'),
    ('Ha_4', 'Hydrogen bond acceptor'),
    ('Hd_4', 'Hydrogen bond donor'),
    ('Hd_4-5', 'Hydrogen bond donor'),
    ('Hd_5-6', 'Hydrogen bond donor'),
    ('Hd_6', 'Hydrogen bond donor'),
    ('+-_any', 'Charged'),
    ('+-_3-4', 'Charged'),
    ('+-_4-5', 'Charged'),
    ('+_any', 'Charged positive'),
    ('H_4', 'Charged pos / H bond / Hphob ar [H]'),
    ('+_4-5', 'Charged positive'),
    ('K_5', 'Charged positive [K]'),
    ('+_5-6', 'Charged positive'),
    ('R_6', 'Charged positive [R]'),
    ('-_any', 'Charged negative'),
    ('D_3', 'Charged negative [D]'),
    ('E_4', 'Charged negative [E]'),
    ('Sm_0-2', 'Small'),
    ('Sm_0-1', 'Small'),
    ('Sm_1-2', 'Small'),
    ('aH_Hig', 'α-Helix propensity - high'),
    # ('aH_Med', 'α-Helix propensity - medium'),
    ('aH_Low', 'α-Helix propensity - low'),
    # ('aH_Min', 'α-Helix propensity - very low'),
    ('G_0', 'α-Helix flexibility [G]'),
    ('P_2', 'α-Helix kink [P]'),
    ('C_2', 'Disulfide-forming (S-S) [C]'),
    ('-', 'Gap (no amino acid)')
])


AMINO_ACID_GROUP_PROPERTIES = OrderedDict([
    ('HY_any', {'display_name_short': 'HY', 'length': 'any'}),
    ('HY_4-5', {'display_name_short': 'HY', 'length': '4-5'}),
    ('HA_any', {'display_name_short': 'HA', 'length': 'any'}),
    ('HA_1-2', {'display_name_short': 'HA', 'length': '1-2'}),
    ('HA_2-3', {'display_name_short': 'HA', 'length': '2-3'}),
    ('HA_3', {'display_name_short': 'HA', 'length': '3'}),
    ('HA_3-4', {'display_name_short': 'HA', 'length': '3-4'}),
    ('M_4', {'display_name_short': 'M', 'length': '4'}),
    ('A_1', {'display_name_short': 'A', 'length': '1'}),
    ('I_', {'display_name_short': 'I', 'length': ''}),
    ('L_', {'display_name_short': 'L', 'length': ''}),
    ('V_', {'display_name_short': 'V', 'length': ''}),
    ('HR_any', {'display_name_short': 'HR', 'length': 'any'}),
    ('HR_4-5', {'display_name_short': 'HR', 'length': '4-5'}),
    ('HR_5', {'display_name_short': 'HR', 'length': '5'}),
    ('HR_5-6', {'display_name_short': 'HR', 'length': '5-6'}),
    ('W_6', {'display_name_short': 'W', 'length': '6'}),
    ('Y_?', {'display_name_short': 'Y', 'length': ''}),
    ('F_', {'display_name_short': 'F', 'length': ''}),
    ('Hb_any', {'display_name_short': 'Hb', 'length': 'any'}),
    ('Hb_2', {'display_name_short': 'Hb', 'length': '2'}),
    ('Hb_3', {'display_name_short': 'Hb', 'length': '3'}),
    ('N_', {'display_name_short': 'N', 'length': ''}),
    ('Q_', {'display_name_short': 'Q', 'length': ''}),
    ('S_', {'display_name_short': 'S', 'length': ''}),
    ('T_', {'display_name_short': 'T', 'length': ''}),
    ('Hu_2-3', {'display_name_short': 'Hu', 'length': '2-3'}),
    ('Hu_3-4', {'display_name_short': 'Hu', 'length': '3-4'}),
    ('Ha_2-3', {'display_name_short': 'Ha', 'length': '2-3'}),
    ('Ha_3', {'display_name_short': 'Ha', 'length': '3'}),
    ('Ha_3-4', {'display_name_short': 'Ha', 'length': '3-4'}),
    ('Ha_4', {'display_name_short': 'Ha', 'length': '4'}),
    ('Hd_4', {'display_name_short': 'Hd', 'length': '4'}),
    ('Hd_4-5', {'display_name_short': 'Hd', 'length': '4-5'}),
    ('Hd_5-6', {'display_name_short': 'Hd', 'length': '5-6'}),
    ('Hd_6', {'display_name_short': 'Hd', 'length': '6'}),
    ('+-_any', {'display_name_short': '+-', 'length': 'any'}),
    ('+-_3-4', {'display_name_short': '+-', 'length': '3-4'}),
    ('+-_4-5', {'display_name_short': '+-', 'length': '4-5'}),
    ('+_any', {'display_name_short': '+', 'length': 'any'}),
    ('H_4', {'display_name_short': 'H', 'length': '4'}),
    ('+_4-5', {'display_name_short': '+', 'length': '4-5'}),
    ('K_5', {'display_name_short': 'K', 'length': '5'}),
    ('+_5-6', {'display_name_short': '+', 'length': '5-6'}),
    ('R_6', {'display_name_short': 'R', 'length': '6'}),
    ('-_any', {'display_name_short': '-', 'length': 'any'}),
    ('D_3', {'display_name_short': 'D', 'length': '3'}),
    ('E_4', {'display_name_short': 'E', 'length': '4'}),
    ('Sm_0-2', {'display_name_short': 'Sm', 'length': 'any'}),
    ('Sm_0-1', {'display_name_short': 'Sm', 'length': '0-1'}),
    ('Sm_1-2', {'display_name_short': 'Sm', 'length': '1-2'}),
    ('aH_Hig', {'display_name_short': 'αH', 'length': 'Hig'}),
    # ('aH_Med', {'display_name_short': 'αH', 'length': 'Med'}),
    # ('aH_Low', {'display_name_short': 'αH', 'length': 'Low'}),
    ('aH_Low', {'display_name_short': 'αH', 'length': 'Min'}),
    ('G_0', {'display_name_short': 'G', 'length': '0'}),
    ('P_2', {'display_name_short': 'P', 'length': '2'}),
    ('C_2', {'display_name_short': 'C', 'length': '2'}),
    ('-', {'display_name_short': '-', 'length': ''})
])


AMINO_ACID_GROUPS_OLD = OrderedDict([
        ('hp',     ('A', 'C', 'F', 'I', 'L', 'M', 'P', 'V', 'W', 'Y')),
        ('alhp',   ('A', 'C', 'I', 'L', 'M', 'P', 'V')),
        ('arhp',   ('F', 'W', 'Y')),
        ('ar',     ('F', 'H', 'W', 'Y')),
        ('pol',    ('D', 'E', 'H', 'K', 'N', 'Q', 'R', 'S', 'T')),
        ('hb',     ('D', 'E', 'H', 'K', 'N', 'Q', 'R', 'S', 'T', 'W', 'Y')),
        ('hbd',    ('H', 'K', 'N', 'Q', 'R', 'S', 'T', 'W', 'Y')),
        ('hba',    ('D', 'E', 'H', 'N', 'Q', 'S', 'T', 'Y')),
        ('charge', ('D', 'E', 'H', 'K', 'R')),
        ('neg',    ('D', 'E')),
        ('pos',    ('H', 'K', 'R')),
        ('lar',    ('E', 'F', 'H', 'K', 'Q', 'R', 'W', 'Y')),
        ('sma',    ('A', 'C', 'D', 'G', 'N', 'P', 'S', 'T', 'V')),
        ('any',    ()),
        ('custom', ()),
    ])

AMINO_ACID_GROUP_NAMES_OLD = OrderedDict([
        ('hp',     'Hydrophobic - All'),
        ('alhp',   'Hydrophobic - Aliphatic'),
        ('arhp',   'Hydrophobic - Aromatic'),
        ('ar',     'Aromatic'),
        ('pol',    'Polar'),
        ('hb',     'H-Bonding'),
        ('hbd',    'H-Bond Donor'),
        ('hba',    'H-Bond Acceptor'),
        ('charge', 'Charge'),
        ('neg',    'Negative charge'),
        ('pos',    'Positive charge'),
        ('lar',    'Large'),
        ('sma',    'Small'),
        ('any',    'Any feature'),
        ('custom', 'Custom'),
    ])

DESIGN_SUBSTITUTION_DICT = {"A":  ["S"],
                            "C":  ["S"],
                            "D":  ["L", "K"],
                            "E":  ["M", "K"],
                            "F":  ["N", "D"],
                            "G":  ["S"],
                            "H":  ["E", "K"],
                            "I":  ["S"],
                            "K":  ["M", "E"],
                            "L":  ["N", "D"],
                            "M":  ["Q", "K"],
                            "N":  ["L"],
                            "P":  ["-"],
                            "Q":  ["M"],
                            "R":  ["M", "E"],
                            "S":  ["V"],
                            "T":  ["V"],
                            "V":  ["S"],
                            "W":  ["Q", "E"],
                            "Y":  ["N", "D"]}

DESIGN_SUBSTITUTION_MATRIX = OrderedDict([
        ('hydrophobic', {
            #'A':[[['L', 'V', 'I']],['Increase size to "block" binding']],
            'C':[['A'],['Remove vdW interactions (and polar)']],
            'F':[['A'],['Remove vdW interaction possibility']],
            'I':[['A'],['Remove vdW interaction possibilities']],
            'L':[['A'],['Remove vdW interaction possibilities']],
            'M':[['A'],['Remove vdW interaction possibilities']],
            #'P':[['A'],['Remove vdW interactions / change the shape of the site Normaly Prolines have a structural role and are dangerous to tamper with']],
            'V':[['A'],['Remove vdW interaction possibility']],
            'R':[['A'],['Remove vdW interaction possibility']],
            'N':[['A'],['Remove vdW interaction possibility']],
            'D':[['A'],['Remove vdW interaction possibility']],
            'Q':[['A'],['Remove vdW interaction possibility']],
            'E':[['A'],['Remove vdW interaction possibility']],
            'H':[['A'],['Remove vdW interaction possibility']],
            'K':[['A'],['Remove vdW interaction possibility']],
            'T':[['A'],['Remove vdW interaction possibility']],
            'W':[['A'],['Remove vdW interaction possibility']],
            'Y':[['A'],['Remove vdW interaction possibility']],
            }
        ),
        ('aromatic', { #same for all types of aromatic interactions #fixme check aro_ion
            'Y':[[['L', 'M'], 'A'],['Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities', 'Remove polar, aromatic and vdW interaction possibilities']],
            'W':[[['L', 'M'], 'A', 'H'],['Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities', 'Remove polar, aromatic and vdW interaction possibilities', 'Weaken aromatic interaction possibilities while retaining polar interaction possibilities']],
            'F':[[['L', 'M'], 'A', 'Y'],['Remove aromatic interaction possibilities while retaining vdW interaction possibilities', 'Remove aromatic and vdW interaction possibilities', 'Prevent Phe-edge to ligand-face aromatic interaction (Should only be attempted when based on a detailed binding mode hypothesis showing the aromatic interaction in question.)']],
            'H':[['A', 'N',['L', 'M']],['Remove polar, aromatic and vdW interaction possibilities', 'Remove aromatic interaction possibilities while retaining polar interaction possibilities', 'Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities']],
            }
        ),
        ('polar', { #same for all types of polar interactions
            'D':[['L', 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'Remove polar interaction possibility']],
            'E':[[['L', 'M'], 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'Remove polar and vdW interaction possibility']],
            'H':[[['L', 'M'], 'A', 'F'],['Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities', 'Remove polar, aromatic and vdW interaction possibilities', 'Remove polar interaction possibility, while retaining aromatic interaction possibilities']],
            'K':[['M', 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'Remove polar and vdW interaction possibility']],
            'N':[['L', 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'Remove polar and vdW interaction possibility']],
            'Q':[[['L', 'M'], 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'A - remove the side chain and all interactions']],
            'R':[[['L', 'M'], 'A'],['Remove polar interaction possibility, while retaining vdW interaction possibilities', 'Remove polar and vdW interaction possibility']],
            'S':[['A'],['Remove polar interaction possibility']],
            'T':[['A', 'V'],['Remove polar and vdW interaction possibility', 'Remove polar interaction possibility, while retaining vdW interaction possibilities']],
            'W':[['F', 'A',['L', 'M']],['Remove polar interaction possibility, while retaining aromatic interaction possibilities', 'Remove polar, aromatic and vdW interaction possibilities', 'Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities']],
            'Y':[['F', 'A',['L', 'M']],['Remove polar interaction possibility, while retaining aromatic interaction possibilities (Aromatic interaction cannot be investigated independently from h-bond as none of the polar residues can confromationally match the Tyr OH)', 'Remove polar, aromatic and vdW interaction possibilities', 'Remove aromatic and polar interaction possibilities while retaining vdW interaction possibilities']],
            }
        ),
        ('unknown', { #empty
            }
        ),
        ('steric', {
            'A':[[['L', 'V']],['Increase size to block the binding site']],
            'C':[[['L', 'I']],['Increase size to block the binding site']],
            'G':[[['A', 'V', 'M']],['Add side chain to block the binding site (Glycines are often structurally important and should be mutated with causion - unless closely related receptors show different residues in equivalent position.)']],
            'S':[['L', 'M'],['Increase size to block the binding site']],
            'T':[['L', 'M'],['Increase size to block the binding site']],
            'P':[['L', 'M'],['Increase size to block the binding site (Prolines are often structurally important and should be mutated with causion - unless closely related receptors show different residues in equivalent position.)']],
        })
    ])

STRUCTURAL_RULES_OLD = {'All': [
    # OrderedDict([('Class', 'All'), ('State', 'all'), ('Definition', 'Contract salt-bridge'), ('Generic Position', 'E in upper half of TM, not facing the membrane'), ('Wt AA', 'E'), ('Mut AA', 'D'), ('Note', '')]),

    OrderedDict([('Class', 'All'), ('State', 'all'), ('Definition', 'Residue Switch Y7x53 switch removal'),
                 ('Generic Position', '7x53'), ('Wt AA', 'Y'), ('Mut AA', 'L'), ('Note', '')]),
    OrderedDict([('Class', 'All'), ('State', 'all'), ('Definition', 'Residue Switch Y7x53 switch removal'),
                 ('Generic Position', '7x53'), ('Wt AA', 'Y'), ('Mut AA', 'A'), ('Note', '')])
],
    'A': [
        OrderedDict([('Class', 'A'), ('State', 'all'), ('Definition', 'Residue Switch Add W3x41'),
                     ('Generic Position', '3x41'), ('Wt AA', 'X'), ('Mut AA', 'W'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '3x49'), ('Wt AA', 'X'), ('Mut AA', 'D'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '3x50'), ('Wt AA', 'X'), ('Mut AA', 'R'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '6x30'), ('Wt AA', 'X'), ('Mut AA', 'E'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) contraction'),
                     ('Generic Position', '3x49'), ('Wt AA', 'E'), ('Mut AA', 'D'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x49'), ('Wt AA', 'D'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x50'), ('Wt AA', 'R'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x50'), ('Wt AA', 'R'), ('Mut AA', 'L'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'all'), ('Definition', 'Residue Switch N6x49 addition'),
                     ('Generic Position', '6x49'), ('Wt AA', 'X'), ('Mut AA', 'N'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Sodium ion site addition'),
                     ('Generic Position', '2x50'), ('Wt AA', 'X'), ('Mut AA', 'D'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Sodium ion site addition'),
                     ('Generic Position', '3x39'), ('Wt AA', 'X'), ('Mut AA', 'S'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Sodium ion site addition'),
                     ('Generic Position', '6x48'), ('Wt AA', 'X'), ('Mut AA', 'W'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'active'), ('Definition', 'Sodium ion site addition'),
                     ('Generic Position', '7x49'), ('Wt AA', 'X'), ('Mut AA', 'N'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '2x50'), ('Wt AA', 'D/E'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '3x39'), ('Wt AA', 'S/T'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '6x48'), ('Wt AA', 'W'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '7x49'), ('Wt AA', 'N'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '2x50'), ('Wt AA', 'D'), ('Mut AA', 'N'), ('Note', '')]),
        OrderedDict([('Class', 'A'), ('State', 'all'), ('Definition', 'Residue Switch Y7x53 addition'),
                     ('Generic Position', '7x53'), ('Wt AA', 'X'), ('Mut AA', 'Y'), ('Note', '')])
    ],
    'B': [
        OrderedDict([('Class', 'B'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '2x43'), ('Wt AA', 'H'), ('Mut AA', 'A'), ('Note', ' (GPCRdb-B# 2x50)')]),
        OrderedDict([('Class', 'B'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x46'), ('Wt AA', 'E'), ('Mut AA', 'A'), ('Note', ' (GPCRdb-B# 3x50)')]),
        OrderedDict([('Class', 'B'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '3x39'), ('Wt AA', 'N'), ('Mut AA', 'A'), ('Note', ' (GPCRdb-C# 4x43)')])],
    'C': [
        OrderedDict([('Class', 'C'), ('State', 'all'), ('Definition', 'Residue Switch  F7x48 addition'),
                     ('Generic Position', '7x48'), ('Wt AA', 'X'), ('Mut AA', 'F'), ('Note', ' (GPCRdb-B# 7x53)')]),
        OrderedDict([('Class', 'C'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '3x50'), ('Wt AA', 'X'), ('Mut AA', 'R'), ('Note', '')]),
        OrderedDict([('Class', 'C'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '3x50'), ('Wt AA', 'X'), ('Mut AA', 'K'), ('Note', '')]),
        OrderedDict([('Class', 'C'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) addition'),
                     ('Generic Position', '6x33'), ('Wt AA', 'X'), ('Mut AA', 'E'), ('Note', ' (GPCRdb-C# 6x35)')]),
        OrderedDict([('Class', 'C'), ('State', 'inactive'), ('Definition', 'Ionic lock (D/ERY) contraction'),
                     ('Generic Position', '6x33'), ('Wt AA', 'E'), ('Mut AA', 'D'), ('Note', ' (GPCRdb-C# 6x35)')]),
        OrderedDict([('Class', 'C'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x50'), ('Wt AA', 'R'), ('Mut AA', 'A'), ('Note', '')]),
        OrderedDict([('Class', 'C'), ('State', 'active'), ('Definition', 'Ionic lock (D/ERY) removal'),
                     ('Generic Position', '3x50'), ('Wt AA', 'R'), ('Mut AA', 'L'), ('Note', '')]),
        OrderedDict([('Class', 'C'), ('State', 'active'), ('Definition', 'Sodium ion site addition'),
                     ('Generic Position', '6x48'), ('Wt AA', 'X'), ('Mut AA', 'W'), ('Note', ' (GPCRdb-C# 6x50)')]),
        OrderedDict([('Class', 'C'), ('State', 'inactive'), ('Definition', 'Sodium ion site removal'),
                     ('Generic Position', '6x48'), ('Wt AA', 'W'), ('Mut AA', 'A'), ('Note', ' (GPCRdb-C# 6x50)')]),
        OrderedDict([('Class', 'C'), ('State', 'all'), ('Definition', 'Residue Switch Y7x53 addition'),
                     ('Generic Position', '7x53'), ('Wt AA', 'X'), ('Mut AA', 'Y'), ('Note', ' (GPCRdb-B# 7x58)')])
    ],
}


STRUCTURAL_RULES = {
    "A": [
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X3x49D",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x49",
            "Mut AA": "D",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "ToDo David",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X3x50R",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x50",
            "Mut AA": "R",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X6x30E",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "6x30",
            "Mut AA": "E",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Contraction",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "E3x49D",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x49",
            "Mut AA": "D",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "E"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "D3x49A",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "CCR5",
            "Generic Position": "3x49",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "ToDo David",
            "Type": "Structure-based",
            "Wt AA": "D"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "R3x50A",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x50",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "R"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "R3x50L ",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "NTR1",
            "Generic Position": "3x50",
            "Mut AA": "L",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "R"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X6x49N",
            "Design Principle": "State switch N6x49",
            "Example structures": "",
            "Generic Position": "6x49",
            "Mut AA": "N",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "D2x50A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "2x50",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "D/E"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "D2x50N",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "2x50",
            "Mut AA": "N",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "D"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "S3x39A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "3x39",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "S/T"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "W6x48A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "6x48",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "W"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "N1x50A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "1x50",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "N"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "N3x35A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "3x35",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "N"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "N7x45A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x45",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "N"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "S7x46A",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x46",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "S"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "Y7x53F",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x53",
            "Mut AA": "F",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "Y"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X2x50D",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "2x50",
            "Mut AA": "D",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X3x39S",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "3x39",
            "Mut AA": "S",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X6x48W",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "6x48",
            "Mut AA": "W",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X1x50N",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "1x50",
            "Mut AA": "N",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X3x35N",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "3x35",
            "Mut AA": "N",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X7x45N",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x45",
            "Mut AA": "N",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X7x46S",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x46",
            "Mut AA": "S",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X7x53Y",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "7x53",
            "Mut AA": "Y",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "A",
            "Definition": "X7x53Y",
            "Design Principle": "State switch Y7x53",
            "Example structures": "",
            "Generic Position": "7x53",
            "Mut AA": "Y",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        }
    ],
    "All": [
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "All",
            "Definition": "Y7x53L",
            "Design Principle": "State switch Y7x53",
            "Example structures": "ADRB1",
            "Generic Position": "7x53",
            "Mut AA": "L",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "Y"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "All",
            "Definition": "Y7x53A",
            "Design Principle": "State switch Y7x53",
            "Example structures": "",
            "Generic Position": "7x53",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "Y"
        }
    ],
    "B": [
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "B",
            "Definition": "H2x43A (GPCRdb-B# 2x50)",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "2x43",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "H"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "B",
            "Definition": "E3x46A (GPCRdb-B# 3x50)",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x46",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "E"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "B",
            "Definition": "N3x39A (GPCRdb-C# 4x43)",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "3x39",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "N"
        }
    ],
    "C": [
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X7x48F (GPCRdb-B# 7x53)",
            "Design Principle": "State switch F7x48",
            "Example structures": "",
            "Generic Position": "7x48",
            "Mut AA": "F",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X3x50R",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x50",
            "Mut AA": "R",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X3x50K",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x50",
            "Mut AA": "K",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X6x33E (GPCRdb-C# 6x35)",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "6x33",
            "Mut AA": "E",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Contraction",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "E6x33D (GPCRdb-C# 6x35)",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "6x33",
            "Mut AA": "D",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "E"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "K3x50A",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "",
            "Generic Position": "3x50",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "R"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "K3x50L ",
            "Design Principle": "Ionic lock (D/ERY)",
            "Example structures": "NTR1",
            "Generic Position": "3x50",
            "Mut AA": "L",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "R"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X6x48W (GPCRdb-C# 6x50)",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "6x48",
            "Mut AA": "W",
            "Note": "",
            "Prio": 5.0,
            "State": "Active",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        },
        {
            "Addition / Removal": "Removal",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "W6x48A (GPCRdb-C# 6x50)",
            "Design Principle": "Sodium ion site",
            "Example structures": "",
            "Generic Position": "6x48",
            "Mut AA": "A",
            "Note": "",
            "Prio": 5.0,
            "State": "Inactive",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "W"
        },
        {
            "Addition / Removal": "Addition",
            "Basis": "Structures",
            "Class": "C",
            "Definition": "X7x53Y (GPCRdb-B# 7x58)",
            "Design Principle": "State switch Y7x53",
            "Example structures": "",
            "Generic Position": "7x53",
            "Mut AA": "Y",
            "Note": "",
            "Prio": 5.0,
            "State": "All",
            "ToDo David": "",
            "Type": "Structure-based",
            "Wt AA": "X"
        }
    ]
}


STRUCTURAL_SWITCHES = {
        "A": [
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x35",
                "AA1 Pos": "2x50",
                "Active1": "D",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "N",
                "Inactive1": "D",
                "Inactive2": "N",
                "Interaction pair": "D2x50-N3x35",
                "Interaction type": "Na+ ion",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x39",
                "AA1 Pos": "2x50",
                "Active1": "D",
                "Active2": "A",
                "Class": "A",
                "Class Pos": "",
                "Cons": "S",
                "Inactive1": "D",
                "Inactive2": "S",
                "Interaction pair": "D2x50-S3x39",
                "Interaction type": "Na+ ion",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x49",
                "AA1 Pos": "2x50",
                "Active1": "D",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "D",
                "Inactive1": "D",
                "Inactive2": "D",
                "Interaction pair": "D2x50-D7x49",
                "Interaction type": "Na+ ion",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x49",
                "AA1 Pos": "2x50",
                "Active1": "D",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "N",
                "Inactive1": "D",
                "Inactive2": "N",
                "Interaction pair": "D2x50-N7x49",
                "Interaction type": "Na+ ion",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x49",
                "AA1 Pos": "2x50",
                "Active1": "N",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "D",
                "Inactive1": "D",
                "Inactive2": "D",
                "Interaction pair": "N2x50-D7x49",
                "Interaction type": "Na+ ion",
                "Match AA1": "D",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x49",
                "AA1 Pos": "2x50",
                "Active1": "A",
                "Active2": "Wt",
                "Class": "A",
                "Class Pos": "",
                "Cons": "N",
                "Inactive1": "D",
                "Inactive2": "Wt",
                "Interaction pair": "A2x50-N7x49",
                "Interaction type": "Na+ ion",
                "Match AA1": "D",
                "Match AA2": "X",
                "Motif": "Sodium ion site",
                "Prio": 2.0,
                "Rotamer Switch": "-",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x49",
                "AA1 Pos": "3x50",
                "Active1": "R",
                "Active2": "Wt",
                "Class": "A",
                "Class Pos": "",
                "Cons": "D",
                "Inactive1": "R",
                "Inactive2": "Wt",
                "Interaction pair": "R3x50-D3x49",
                "Interaction type": "Salt-bridge",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "5x58",
                "AA1 Pos": "3x50",
                "Active1": "R",
                "Active2": "Y",
                "Class": "A",
                "Class Pos": "",
                "Cons": "Y",
                "Inactive1": "S",
                "Inactive2": "S",
                "Interaction pair": "R3x50-Y5x58",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x30",
                "AA1 Pos": "3x50",
                "Active1": "R",
                "Active2": "A",
                "Class": "A",
                "Class Pos": "",
                "Cons": "E",
                "Inactive1": "R",
                "Inactive2": "E",
                "Interaction pair": "R3x50-E6x30",
                "Interaction type": "Salt-bridge",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x37",
                "AA1 Pos": "3x50",
                "Active1": "R",
                "Active2": "A",
                "Class": "A",
                "Class Pos": "",
                "Cons": "L",
                "Inactive1": "R",
                "Inactive2": "L",
                "Interaction pair": "R3x50-L6x37",
                "Interaction type": "Blocking R3x50",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Strengthens P6x50 kink by stacking to F6x51",
                "%": "",
                "AA2 Pos": "3x40",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "A",
                "Class Pos": "",
                "Cons": "I",
                "Inactive1": "W",
                "Inactive2": "I",
                "Interaction pair": "W6x48-I3x40",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Strengthens P6x50 kink by stacking to F6x51",
                "%": "",
                "AA2 Pos": "6x44",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "F",
                "Inactive1": "W",
                "Inactive2": "F",
                "Interaction pair": "W6x48-F6x44",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Strengthens P6x50 kink by stacking to F6x51",
                "%": "",
                "AA2 Pos": "7x41",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "S",
                "Class": "A",
                "Class Pos": "",
                "Cons": "A",
                "Inactive1": "W",
                "Inactive2": "A",
                "Interaction pair": "W6x48-A7x41",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Strengthens P6x50 kink by stacking to F6x51",
                "%": "",
                "AA2 Pos": "7x41",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "V",
                "Class": "A",
                "Class Pos": "",
                "Cons": "A",
                "Inactive1": "W",
                "Inactive2": "A",
                "Interaction pair": "W6x48-A7x41",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "2x43",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "A",
                "Class": "A",
                "Class Pos": "",
                "Cons": "I",
                "Inactive1": "Y",
                "Inactive2": "I",
                "Interaction pair": "Y7x53-I2x43",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": 73.0,
                "AA2 Pos": "3x43",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "L",
                "Class": "A",
                "Class Pos": "",
                "Cons": "L",
                "Inactive1": "Y",
                "Inactive2": "A",
                "Interaction pair": "Y7x53-L3x43",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": 56.0,
                "AA2 Pos": "3x46",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "I",
                "Class": "A",
                "Class Pos": "",
                "Cons": "I",
                "Inactive1": "Y",
                "Inactive2": "A",
                "Interaction pair": "Y7x53-I3x46",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 0
            }
        ],
        "B": [
            {
                "": "",
                "%": "",
                "AA2 Pos": "2x43",
                "AA1 Pos": "3x46",
                "Active1": "E",
                "Active2": "F",
                "Class": "B",
                "Class Pos": "3x50",
                "Cons": "H",
                "Inactive1": "E",
                "Inactive2": "H",
                "Interaction pair": "E3x46-H2x43",
                "Interaction type": "Salt-bridge",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x53",
                "AA1 Pos": "3x46",
                "Active1": "E",
                "Active2": "Y",
                "Class": "B",
                "Class Pos": "3x50",
                "Cons": "Y",
                "Inactive1": "E",
                "Inactive2": "F",
                "Interaction pair": "E3x46-Y7x53",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "2x43",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "A",
                "Class": "B",
                "Class Pos": "7x57",
                "Cons": "H",
                "Inactive1": "Y",
                "Inactive2": "H",
                "Interaction pair": "Y7x53-H2x43",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "B1: 100%, B2: A",
                "AA2 Pos": "6x37",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "A",
                "Class": "B",
                "Class Pos": "7x57",
                "Cons": "T",
                "Inactive1": "Y",
                "Inactive2": "T",
                "Interaction pair": "Y7x53-T6x37",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": ""
            },
            {
                "": "",
                "%": 77.0,
                "AA2 Pos": "3x46",
                "AA1 Pos": "7x53",
                "Active1": "Y",
                "Active2": "A",
                "Class": "B",
                "Class Pos": "7x57",
                "Cons": "E",
                "Inactive1": "Y",
                "Inactive2": "E",
                "Interaction pair": "Y7x53-E3x46",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": ""
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "8x49",
                "AA1 Pos": "6x32",
                "Active1": "R",
                "Active2": "Wt",
                "Class": "B",
                "Class Pos": "6x37",
                "Cons": "E",
                "Inactive1": "A",
                "Inactive2": "Wt",
                "Interaction pair": "R6x32-E8x49",
                "Interaction type": "Salt-bridge",
                "Match AA1": "RK",
                "Match AA2": "E",
                "Motif": "",
                "Prio": 2.0,
                "Rotamer Switch": "6x37",
                "Show green columns in StabMutAnalyzer": ""
            }
        ],
        "B1": [
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x47",
                "AA1 Pos": "6x48",
                "Active1": "E",
                "Active2": "H",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "H",
                "Inactive1": "E",
                "Inactive2": "V",
                "Interaction pair": "E6x48-H6x47",
                "Interaction type": "Salt-bridge",
                "Match AA1": "E",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "E6x48",
                "Show green columns in StabMutAnalyzer": 0
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x45",
                "AA1 Pos": "6x48",
                "Active1": "E",
                "Active2": "A",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "Q",
                "Inactive1": "E",
                "Inactive2": "Q",
                "Interaction pair": "E6x48-Q7x45",
                "Interaction type": "H-bond",
                "Match AA1": "E",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "E6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "2x53",
                "AA1 Pos": "6x48",
                "Active1": "E",
                "Active2": "M",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "R",
                "Inactive1": "E",
                "Inactive2": "R",
                "Interaction pair": "E6x48-R2x53",
                "Interaction type": "Salt-bridge",
                "Match AA1": "E",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "E6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "5x44",
                "AA1 Pos": "6x48",
                "Active1": "E",
                "Active2": "M",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "R",
                "Inactive1": "E",
                "Inactive2": "R",
                "Interaction pair": "E6x48-R5x44",
                "Interaction type": "Salt-bridge",
                "Match AA1": "E",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "E6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x45",
                "AA1 Pos": "6x48",
                "Active1": "Y",
                "Active2": "M",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "Q",
                "Inactive1": "Y",
                "Inactive2": "Q",
                "Interaction pair": "Y6x48-Q7x45",
                "Interaction type": "H-bond",
                "Match AA1": "Y",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x36",
                "AA1 Pos": "6x48",
                "Active1": "Y",
                "Active2": "A",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "H",
                "Inactive1": "Y",
                "Inactive2": "H",
                "Interaction pair": "Y6x48-H3x36",
                "Interaction type": "H-bond",
                "Match AA1": "Y",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x40",
                "AA1 Pos": "6x48",
                "Active1": "Y",
                "Active2": "L",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "Y",
                "Inactive1": "Y",
                "Inactive2": "Y",
                "Interaction pair": "Y6x48-Y3x40",
                "Interaction type": "Aromatic",
                "Match AA1": "Y",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x45",
                "AA1 Pos": "6x48",
                "Active1": "F",
                "Active2": "M",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "Q",
                "Inactive1": "F",
                "Inactive2": "Q",
                "Interaction pair": "F6x48-Q7x45",
                "Interaction type": "H-bond",
                "Match AA1": "F",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x36",
                "AA1 Pos": "6x48",
                "Active1": "F",
                "Active2": "A",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "V",
                "Inactive1": "F",
                "Inactive2": "V",
                "Interaction pair": "F6x48-V3x36",
                "Interaction type": "H-bond",
                "Match AA1": "F",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x40",
                "AA1 Pos": "6x48",
                "Active1": "F",
                "Active2": "L",
                "Class": "B1",
                "Class Pos": "6x53",
                "Cons": "Y",
                "Inactive1": "F",
                "Inactive2": "Y",
                "Interaction pair": "F6x48-Y3x40",
                "Interaction type": "Aromatic",
                "Match AA1": "F",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "Ar6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x28",
                "AA1 Pos": "6x30",
                "Active1": "R",
                "Active2": "A",
                "Class": "B1",
                "Class Pos": "6x35",
                "Cons": "DS",
                "Inactive1": "A",
                "Inactive2": "D",
                "Interaction pair": "R6x30-DS6x28",
                "Interaction type": "Salt-bridge",
                "Match AA1": "RK",
                "Match AA2": "D",
                "Motif": "-",
                "Prio": 2.0,
                "Rotamer Switch": "6x30",
                "Show green columns in StabMutAnalyzer": ""
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x28",
                "AA1 Pos": "6x30",
                "Active1": "R",
                "Active2": "A",
                "Class": "B1",
                "Class Pos": "6x35",
                "Cons": "DS",
                "Inactive1": "A",
                "Inactive2": "D",
                "Interaction pair": "R6x30-DS6x28",
                "Interaction type": "Salt-bridge",
                "Match AA1": "RK",
                "Match AA2": "D",
                "Motif": "-",
                "Prio": 2.0,
                "Rotamer Switch": "6x30",
                "Show green columns in StabMutAnalyzer": ""
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x28",
                "AA1 Pos": "6x30",
                "Active1": "Y",
                "Active2": "Wt",
                "Class": "B1",
                "Class Pos": "6x35",
                "Cons": "DS",
                "Inactive1": "A",
                "Inactive2": "Wt",
                "Interaction pair": "Y6x30-DS6x28",
                "Interaction type": "?",
                "Match AA1": "Y",
                "Match AA2": "X",
                "Motif": "-",
                "Prio": 2.0,
                "Rotamer Switch": "6x30",
                "Show green columns in StabMutAnalyzer": ""
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x28",
                "AA1 Pos": "6x30",
                "Active1": "Y",
                "Active2": "Wt",
                "Class": "B1",
                "Class Pos": "6x35",
                "Cons": "DS",
                "Inactive1": "A",
                "Inactive2": "Wt",
                "Interaction pair": "Y6x30-DS6x28",
                "Interaction type": "?",
                "Match AA1": "Y",
                "Match AA2": "X",
                "Motif": "-",
                "Prio": 2.0,
                "Rotamer Switch": "6x30",
                "Show green columns in StabMutAnalyzer": ""
            }
        ],
        "B2": [
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x40",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "L",
                "Class": "B2",
                "Class Pos": "6x53",
                "Cons": "F",
                "Inactive1": "W",
                "Inactive2": "F",
                "Interaction pair": "W6x48-F3x40",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "7x45",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "B2",
                "Class Pos": "6x53",
                "Cons": "N",
                "Inactive1": "W",
                "Inactive2": "N",
                "Interaction pair": "W6x48-N7x45",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "3x36",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "B2",
                "Class Pos": "6x53",
                "Cons": "F",
                "Inactive1": "W",
                "Inactive2": "F",
                "Interaction pair": "W6x48-F3x36",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x44",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "B2",
                "Class Pos": "6x53",
                "Cons": "L",
                "Inactive1": "W",
                "Inactive2": "L",
                "Interaction pair": "W6x48-L6x44",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "2x43",
                "AA1 Pos": "7x53",
                "Active1": "H",
                "Active2": "A",
                "Class": "B2",
                "Class Pos": "7x57",
                "Cons": "H",
                "Inactive1": "H",
                "Inactive2": "H",
                "Interaction pair": "H7x53-H2x43",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": 77.0,
                "AA2 Pos": "3x46",
                "AA1 Pos": "7x53",
                "Active1": "H",
                "Active2": "A",
                "Class": "B2",
                "Class Pos": "7x57",
                "Cons": "E",
                "Inactive1": "H",
                "Inactive2": "E",
                "Interaction pair": "H7x53-E3x46",
                "Interaction type": "Salt-bridge",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM7 NPxxY",
                "Prio": 2.0,
                "Rotamer Switch": "Y7x53",
                "Show green columns in StabMutAnalyzer": 1
            }
        ],
        "C": [
            {
                "": "",
                "%": "",
                "AA2 Pos": "12x53",
                "AA1 Pos": "3x46",
                "Active1": "K",
                "Active2": "A",
                "Class": "C",
                "Class Pos": "3x50",
                "Cons": "S",
                "Inactive1": "K",
                "Inactive2": "S",
                "Interaction pair": "K3x46-S12x53",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "",
                "%": "",
                "AA2 Pos": "6x33",
                "AA1 Pos": "3x46",
                "Active1": "K",
                "Active2": "A",
                "Class": "C",
                "Class Pos": "3x50",
                "Cons": "E",
                "Inactive1": "K",
                "Inactive2": "E",
                "Interaction pair": "K3x46-E6x33",
                "Interaction type": "Salt-bridge",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM3 DRY, ionic lock",
                "Prio": 2.0,
                "Rotamer Switch": "R3x50",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Rotamer switch in the mGluR5 structures",
                "%": "",
                "AA2 Pos": "3x40",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "L",
                "Class": "C",
                "Class Pos": "6x50",
                "Cons": "Y",
                "Inactive1": "W",
                "Inactive2": "Y",
                "Interaction pair": "W6x48-Y3x40",
                "Interaction type": "Aromatic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Rotamer switch in the mGluR5 structures",
                "%": "",
                "AA2 Pos": "7x45",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "C",
                "Class Pos": "6x50",
                "Cons": "S",
                "Inactive1": "W",
                "Inactive2": "S",
                "Interaction pair": "W6x48-S7x45",
                "Interaction type": "H-bond",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Rotamer switch in the mGluR5 structures",
                "%": "",
                "AA2 Pos": "5x44",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "C",
                "Class Pos": "6x50",
                "Cons": "L",
                "Inactive1": "W",
                "Inactive2": "L",
                "Interaction pair": "W6x48-L5x44",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            },
            {
                "": "Rotamer switch in the mGluR5 structures",
                "%": "",
                "AA2 Pos": "5x51",
                "AA1 Pos": "6x48",
                "Active1": "W",
                "Active2": "A",
                "Class": "C",
                "Class Pos": "6x50",
                "Cons": "M",
                "Inactive1": "W",
                "Inactive2": "M",
                "Interaction pair": "W6x48-M5x51",
                "Interaction type": "Hydrophobic",
                "Match AA1": "X",
                "Match AA2": "X",
                "Motif": "TM6 CWxP",
                "Prio": 2.0,
                "Rotamer Switch": "W6x48",
                "Show green columns in StabMutAnalyzer": 1
            }
        ]
    }

G_PROTEIN_SEGMENTS = OrderedDict([
        ('Full', ['G.HN', 'G.hns1', 'G.S1', 'G.s1h1', 'G.H1', 'G.h1ha', 'H.HA', 'H.hahb', 'H.HB', 'H.hbhc', 'H.HC', 'H.hchd', 'H.HD', 'H.hdhe', 'H.HE', 'H.hehf', 'H.HF', 'G.hfs2', 'G.S2', 'G.s2s3', 'G.S3', 'G.s3h2', 'G.H2', 'G.h2s4', 'G.S4', 'G.s4h3', 'G.H3', 'G.h3s5', 'G.S5', 'G.s5hg', 'G.HG', 'G.hgh4', 'G.H4', 'G.h4s6', 'G.S6', 'G.s6h5', 'G.H5']),
        ('Structured', ['G.HN', 'G.S1', 'G.H1', 'H.HA', 'H.HB', 'H.HC', 'H.HD', 'H.HE', 'H.HF', 'G.S2', 'G.S3', 'G.H2', 'G.S4', 'G.H3', 'G.S5', 'G.HG', 'G.H4', 'G.S6', 'G.H5']),
    ])

ARRESTIN_SEGMENTS = OrderedDict([
        ('Full', ['ns1', 'S1', 's1s2', 'S2', 's2s3', 'S3',
       's3s4', 'S4', 's4s5', 'S5', 's5s6', 'S6',
       's6h1', 'H1', 'h1s7', 'S7', 's7s8', 'S8',
       's8s9', 'S9', 's9s10', 'S10', 's10s11', 'S11',
       's11s12', 'S12', 's12s13', 'S13', 's13s14', 'S14',
       's14s15', 'S15', 's15s16', 'S16', 's16s17', 'S17',
       's17s18', 'S18', 's18s19', 'S19', 's19s20', 'S20', 's20c']),
        ('Structured', ['S1', 'S2', 'S3',
       'S4', 'S5', 'S6', 'H1', 'S7', 'S8',
       'S9', 'S10', 'S11', 'S12', 'S13', 'S14',
       'S15', 'S16', 'S17', 'S18', 'S19', 'S20']),
    ])

G_PROTEIN_DISPLAY_NAME = { # Alpha
                           'GNAS2':'Gs', 'GNAL':'Golf',
                           'GNAI1':'Gi1', 'GNAI2':'Gi2', 'GNAI3':'Gi3', 'GNAT1':'Gt1', 'GNAT2':'Gt2', 'GNAT3':'Ggust', 'GNAZ':'Gz', 'GNAO':'Go',
                           'GNAQ':'Gq', 'GNA11':'G11', 'GNA14':'G14', 'GNA15':'G15',
                           'GNA12':'G12', 'GNA13':'G13',
                           'GPa1':'GPa1', 'GPA1':'GPa1',
                           # Beta
                           'G(I)/G(S)/G(T) subunit beta-1':'G&beta;1',
                           'BJ4_G0051350.mRNA.1.CDS.1':'STE4 isoform 1',
                           # Gamma
                           'G(T) subunit gamma-T1':'G&gamma;T1', 'G(I)/G(S)/G(O) subunit gamma-2':'G&gamma;2',
                           'subunit gamma':'G&gamma;'}

ARRESTIN_DISPLAY_NAME = {'arrs_mouse':'S-arrestin', 'arrs_bovin':'S-arrestin', 'arrb1_human':'Beta-arrestin-1', 'arrb1_rat':'Beta-arrestin-1'}
