# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='sodium',
            field=models.BooleanField(default=False),
        ),
    ]
