# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureModelRMSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.CharField(max_length=4)),
                ('service', models.CharField(max_length=10)),
                ('version', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date', models.DateField(null=True)),
                ('overall_all', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('overall_backbone', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('TM_all', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('TM_backbone', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'structure_model_rmsd',
            },
        ),
        migrations.CreateModel(
            name='StructureModelStatsRotamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=6)),
                ('sequence_number', models.IntegerField()),
                ('generic_number', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'structure_model_stats_rotamer',
            },
        ),
        migrations.CreateModel(
            name='StructureModelStatsSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=6)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('start_gn', models.CharField(max_length=5, null=True)),
                ('end_gn', models.CharField(max_length=5, null=True)),
                ('backbone_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_model_stats_segment',
            },
        ),
        migrations.RemoveField(
            model_name='structuremodelanomalies',
            name='anomaly',
        ),
        migrations.RemoveField(
            model_name='structuremodelanomalies',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelanomalies',
            name='template',
        ),
        migrations.RemoveField(
            model_name='structuremodellooptemplates',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodellooptemplates',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='structuremodellooptemplates',
            name='template',
        ),
        migrations.RemoveField(
            model_name='structuremodelresidues',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelresidues',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='structuremodelresidues',
            name='rotamer',
        ),
        migrations.RemoveField(
            model_name='structuremodelresidues',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='structuremodelresidues',
            name='template',
        ),
        migrations.AddField(
            model_name='structuremodel',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StructureModelAnomalies',
        ),
        migrations.DeleteModel(
            name='StructureModelLoopTemplates',
        ),
        migrations.DeleteModel(
            name='StructureModelResidues',
        ),
        migrations.AddField(
            model_name='structuremodelstatssegment',
            name='homology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel'),
        ),
        migrations.AddField(
            model_name='structuremodelstatsrotamer',
            name='homology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel'),
        ),
        migrations.AddField(
            model_name='structuremodelstatsrotamer',
            name='model_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModelStatsSegment'),
        ),
        migrations.AddField(
            model_name='structuremodelstatsrotamer',
            name='rotamer_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='homology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel'),
        ),
    ]
