# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0001_initial'),
        ('structure', '0002_structure_refined'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRefinedSeqSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField()),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_refined_seqsim',
            },
        ),
        migrations.CreateModel(
            name='StructureRefinedStatsRotamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backbone_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('residue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
                ('rotamer_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_refined_stats_rotamer',
            },
        ),
    ]
