# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20161117_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamer',
            name='missing_atoms',
            field=models.BooleanField(default=False),
        ),
    ]
