# Generated by Django 2.0.4 on 2018-06-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20180117_1457'),
        ('structure', '0003_structurecomplexmodel_structurecomplexmodelseqsim_structurecomplexmodelstatsrotamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurecomplexmodel',
            name='prot_signprot_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinGProteinPair'),
        ),
    ]
