# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0001_initial'),
        ('structure', '0003_rotamer_missing_atoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuremodelstatssegment',
            name='backbone_template',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatssegment',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='generic_number',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='model_segment',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='sequence_number',
        ),
        migrations.AddField(
            model_name='structuremodelstatsrotamer',
            name='backbone_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='structuremodelstatsrotamer',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
        migrations.AlterField(
            model_name='structuremodelstatsrotamer',
            name='rotamer_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Structure'),
        ),
        migrations.DeleteModel(
            name='StructureModelStatsSegment',
        ),
    ]
