# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0001_initial'),
        ('structure', '0003_rotamer_missing_atoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='interactions',
            field=models.ManyToManyField(to='contactnetwork.ResiduePairInteraction'),
        ),
    ]
