# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_structure_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='interactions',
        ),
    ]
