# Generated by Django 2.0.4 on 2018-06-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_structurecomplexmodel_prot_signprot_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurecomplexmodel',
            name='prot_signprot_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='protein.ProteinGProteinPair'),
        ),
    ]
