# Generated by Django 2.0.4 on 2018-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signprot', '0005_auto_20180809_1647'),
        ('structure', '0005_auto_20180625_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='signprot_complex',
            field=models.ManyToManyField(related_name='signprot_complex', to='signprot.SignprotComplex'),
        ),
    ]
