# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_structure_annotated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureModelSeqSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField()),
            ],
            options={
                'db_table': 'structure_model_seqsim',
            },
        ),
        migrations.AlterField(
            model_name='structuremodel',
            name='version',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='structuremodelseqsim',
            name='homology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel'),
        ),
        migrations.AddField(
            model_name='structuremodelseqsim',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
    ]
