# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_structuremodel_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
