# Generated by Django 2.0.4 on 2018-12-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20180913_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_text', models.TextField()),
            ],
            options={
                'db_table': 'stats_text',
            },
        ),
        migrations.RemoveField(
            model_name='structurecomplexmodel',
            name='pdb',
        ),
        migrations.RemoveField(
            model_name='structuremodel',
            name='pdb',
        ),
        migrations.AddField(
            model_name='structurecomplexmodel',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
        migrations.AddField(
            model_name='structuremodel',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.PdbData'),
        ),
        migrations.AddField(
            model_name='structurecomplexmodel',
            name='stats_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='structure.StatsText'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuremodel',
            name='stats_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='structure.StatsText'),
            preserve_default=False,
        ),
    ]
