# Generated by Django 2.0.4 on 2018-12-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20181212_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='stats_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.StatsText'),
        ),
    ]
