# Generated by Django 2.0.8 on 2019-03-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_structure_stats_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='signprot_complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signprot_complex', to='signprot.SignprotComplex'),
        ),
    ]
