# Generated by Django 2.0.4 on 2019-03-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0006_remove_proteinconformation_template_structure'),
        ('structure', '0010_auto_20190307_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureComplexProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=1)),
                ('protein_conformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_complex_protein',
            },
        ),
    ]
