# Generated by Django 2.0.8 on 2019-04-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_structurevectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurevectors',
            name='center_axis',
            field=models.CharField(max_length=200),
        ),
    ]
