# Generated by Django 2.0.8 on 2019-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_auto_20190410_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurevectors',
            name='tm1_axis',
        ),
        migrations.AddField(
            model_name='structurevectors',
            name='tm1_angle',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='structurevectors',
            name='translation',
            field=models.CharField(max_length=100, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structurevectors',
            name='center_axis',
            field=models.CharField(max_length=100),
        ),
    ]
