# Generated by Django 2.0.8 on 2019-04-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_auto_20190412_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurevectors',
            name='tm1_angle',
        ),
    ]
