# Generated by Django 2.0.8 on 2019-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_remove_structurevectors_tm1_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='contact_representative',
            field=models.BooleanField(default=False),
        ),
    ]
