# Generated by Django 2.0.8 on 2019-06-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_structure_contact_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='contact_representative_score',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
