# Generated by Django 2.0.8 on 2019-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_structure_contact_representative_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='active_class_contacts_fraction',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='inactive_class_contacts_fraction',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
