# Generated by Django 2.0.8 on 2019-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_auto_20190605_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='distance_representative',
            field=models.BooleanField(default=True),
        ),
    ]
