# Generated by Django 2.0.4 on 2019-10-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
        ('structure', '0021_structure_tm6_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureExtraProteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=20, null=True)),
                ('chain', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=20)),
                ('wt_coverage', models.IntegerField()),
                ('protein_conformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
                ('wt_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'extra_proteins',
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='extra_proteins',
            field=models.ManyToManyField(related_name='extra_proteins', to='structure.StructureExtraProteins'),
        ),
    ]
