# Generated by Django 2.0.4 on 2019-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0022_auto_20191017_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureextraproteins',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
