# Generated by Django 2.0.8 on 2019-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_auto_20191018_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='closest_to_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='mammal',
            field=models.BooleanField(default=False),
        ),
    ]
