# Generated by Django 2.0.8 on 2020-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_auto_20191211_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='gprot_bound_likeness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
