# Generated by Django 3.0.3 on 2020-06-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0025_structure_gprot_bound_likeness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurecomplexmodel',
            name='prot_signprot_pair',
        ),
    ]
