# Generated by Django 3.0.3 on 2020-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_remove_structurecomplexmodel_prot_signprot_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureextraproteins',
            name='wt_coverage',
            field=models.IntegerField(null=True),
        ),
    ]
