# Generated by Django 3.0.3 on 2020-08-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_auto_20200605_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureextraproteins',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
    ]
