# Generated by Django 3.0.3 on 2020-10-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_auto_20200831_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='extra_proteins',
        ),
    ]
