# Generated by Django 3.0.3 on 2020-10-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200511_1818'),
        ('structure', '0031_auto_20201021_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='author_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_state', to='protein.ProteinState'),
        ),
    ]
