# Generated by Django 3.0.3 on 2020-11-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0033_auto_20201110_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='version',
            field=models.DateField(null=True),
        ),
    ]
