# Generated by Django 3.0.3 on 2020-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0034_structuremodelrmsd_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='TM_all',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
