# Generated by Django 3.0.3 on 2020-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0035_structuremodelrmsd_tm_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='ECL3',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='notes',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='overall_all',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='overall_backbone',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='seq_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='structuremodelrmsd',
            name='seq_sim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='ECL1',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='ECL2',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='H8',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='ICL1',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='ICL2',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='TM_all',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='structuremodelrmsd',
            name='TM_backbone',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
