# Generated by Django 3.0.3 on 2021-02-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_auto_20201126_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurecomplexmodelstatsrotamer',
            name='backbone_template',
        ),
        migrations.RemoveField(
            model_name='structurecomplexmodelstatsrotamer',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structurecomplexmodelstatsrotamer',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='structurecomplexmodelstatsrotamer',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='structurecomplexmodelstatsrotamer',
            name='rotamer_template',
        ),
        migrations.RemoveField(
            model_name='structuremodelseqsim',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelseqsim',
            name='template',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='backbone_template',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='homology_model',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='structuremodelstatsrotamer',
            name='rotamer_template',
        ),
        migrations.RemoveField(
            model_name='structurerefinedseqsim',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='structurerefinedseqsim',
            name='template',
        ),
        migrations.RemoveField(
            model_name='structurerefinedstatsrotamer',
            name='backbone_template',
        ),
        migrations.RemoveField(
            model_name='structurerefinedstatsrotamer',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='structurerefinedstatsrotamer',
            name='rotamer_template',
        ),
        migrations.RemoveField(
            model_name='structurerefinedstatsrotamer',
            name='structure',
        ),
        migrations.DeleteModel(
            name='StructureComplexModelSeqSim',
        ),
        migrations.DeleteModel(
            name='StructureComplexModelStatsRotamer',
        ),
        migrations.DeleteModel(
            name='StructureModelSeqSim',
        ),
        migrations.DeleteModel(
            name='StructureModelStatsRotamer',
        ),
        migrations.DeleteModel(
            name='StructureRefinedSeqSim',
        ),
        migrations.DeleteModel(
            name='StructureRefinedStatsRotamer',
        ),
    ]
