# Generated by Django 3.0.3 on 2021-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0037_auto_20210224_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuretype',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
