# Generated by Django 3.0.3 on 2022-01-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0038_auto_20211026_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureengineering',
            name='description',
        ),
        migrations.RemoveField(
            model_name='structureengineering',
            name='protein_segment',
        ),
        migrations.RemoveField(
            model_name='structureengineering',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='structuresegment',
            name='protein_segment',
        ),
        migrations.RemoveField(
            model_name='structuresegment',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='structuresegmentmodeling',
            name='protein_segment',
        ),
        migrations.RemoveField(
            model_name='structuresegmentmodeling',
            name='structure',
        ),
        migrations.DeleteModel(
            name='StructureCoordinates',
        ),
        migrations.DeleteModel(
            name='StructureCoordinatesDescription',
        ),
        migrations.DeleteModel(
            name='StructureEngineering',
        ),
        migrations.DeleteModel(
            name='StructureEngineeringDescription',
        ),
        migrations.DeleteModel(
            name='StructureSegment',
        ),
        migrations.DeleteModel(
            name='StructureSegmentModeling',
        ),
    ]
