# Generated by Django 2.2.1 on 2022-02-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0039_auto_20220126_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureComplexProtein',
        ),
    ]
