# Generated by Django 3.0.3 on 2022-08-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20180504_1417'),
        ('structure', '0040_delete_structurecomplexprotein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuremodel',
            name='main_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AlterField(
            model_name='structuremodel',
            name='stats_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.StatsText'),
        ),
        migrations.CreateModel(
            name='StructureModelpLDDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pLDDT', models.DecimalField(decimal_places=2, max_digits=4)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue')),
                ('structure_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.StructureModel')),
            ],
            options={
                'db_table': 'structure_model_plddt',
            },
        ),
    ]
