# Generated by Django 3.0.3 on 2023-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0024_ligandpeptidestructure_model'),
        ('common', '0006_releasestatistics_database'),
        ('structure', '0042_auto_20220916_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodel',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='structuremodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.StructureType'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='pdb_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='resolution',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
