# Generated by Django 3.1.7 on 2023-02-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0023_auto_20230210_1010'),
        ('structure', '0042_auto_20220916_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodel',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand'),
        ),
        migrations.AddField(
            model_name='structuremodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structuretype'),
        ),
    ]
