# Generated by Django 3.0.3 on 2023-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0043_auto_20230712_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='build_check',
            field=models.BooleanField(default=False),
        ),
    ]
