# Generated by Django 3.1.7 on 2023-02-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
        ('structure', '0043_auto_20230210_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='pdb_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='resolution',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
