# Generated by Django 3.2.18 on 2023-08-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0044_structure_build_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuremodel',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='structuremodel',
            name='type',
        ),
        migrations.CreateModel(
            name='StructureAFScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('iptm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pae_mean', models.DecimalField(decimal_places=2, max_digits=4)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_af_scores',
            },
        ),
    ]
