# Generated by Django 3.2.18 on 2023-09-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0045_auto_20230825_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodelplddt',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
