# Generated by Django 3.2.18 on 2023-09-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0046_structuremodelplddt_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuremodelplddt',
            name='structure_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structuremodel'),
        ),
    ]
