# Generated by Django 2.2.17 on 2024-09-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0047_alter_structuremodelplddt_structure_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRFAAScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pae_7tm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('plddt_mean', models.DecimalField(decimal_places=2, max_digits=4)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_rfaa_scores',
            },
        ),
    ]
