# Generated by Django 3.0.3 on 2024-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0048_structurerfaascores'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuremodel',
            name='model_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
