# Generated by Django 2.2.17 on 2026-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0050_structuremodelscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
