# Generated by Django 2.2.17 on 2026-09-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0050_structureauxiliarysmallmolecule'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StructureModelScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_json', models.TextField(null=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'db_table': 'structure_model_scores',
            },
        ),
    ]
