# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('amino_acid', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['sequence_number'],
                'db_table': 'residue',
            },
        ),
        migrations.CreateModel(
            name='ResidueDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('value_text', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidueDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResidueGenericNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=12)),
                ('protein_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_numbers', to='protein.ProteinSegment')),
            ],
            options={
                'db_table': 'residue_generic_number',
            },
        ),
        migrations.CreateModel(
            name='ResidueGenericNumberEquivalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=12)),
                ('default_generic_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueGenericNumber')),
            ],
            options={
                'db_table': 'residue_generic_number_equivalent',
            },
        ),
        migrations.CreateModel(
            name='ResidueNumberingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueNumberingScheme')),
            ],
            options={
                'db_table': 'residue_generic_numbering_scheme',
            },
        ),
        migrations.CreateModel(
            name='ResiduePositionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('residue_position', models.ManyToManyField(to='residue.ResidueGenericNumberEquivalent')),
            ],
            options={
                'db_table': 'residue_position_set',
            },
        ),
        migrations.CreateModel(
            name='ResidueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('residue', models.ManyToManyField(to='residue.Residue')),
            ],
            options={
                'db_table': 'residue_set',
            },
        ),
        migrations.AddField(
            model_name='residuegenericnumberequivalent',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueNumberingScheme'),
        ),
        migrations.AddField(
            model_name='residuegenericnumber',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueNumberingScheme'),
        ),
        migrations.AddField(
            model_name='residuedatapoint',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueDataType'),
        ),
        migrations.AddField(
            model_name='residuedatapoint',
            name='residue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='residue.Residue'),
        ),
        migrations.AddField(
            model_name='residue',
            name='alternative_generic_numbers',
            field=models.ManyToManyField(related_name='alternative', to='residue.ResidueGenericNumber'),
        ),
        migrations.AddField(
            model_name='residue',
            name='display_generic_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='residue.ResidueGenericNumber'),
        ),
        migrations.AddField(
            model_name='residue',
            name='generic_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='residue.ResidueGenericNumber'),
        ),
        migrations.AddField(
            model_name='residue',
            name='protein_conformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinConformation'),
        ),
        migrations.AddField(
            model_name='residue',
            name='protein_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinSegment'),
        ),
        migrations.AlterUniqueTogether(
            name='residuegenericnumberequivalent',
            unique_together={('scheme', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='residuegenericnumber',
            unique_together={('scheme', 'label')},
        ),
    ]
