# Generated by Django 2.0.1 on 2018-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuepositionset',
            name='protein_group',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residuepositionset',
            name='set_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
