# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_auto_20170929_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuegenericnumberequivalent',
            name='label',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
