# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0003_auto_20170929_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidueDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResidueDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='residuedatapoint',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueDataType'),
        ),
        migrations.AddField(
            model_name='residuedatapoint',
            name='residue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.Residue'),
        ),
    ]
