# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0004_auto_20171208_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuedatapoint',
            name='value_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residuedatapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
