# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
        ('structure', '0001_initial'),
        ('common', '0001_initial'),
        ('residue', '0001_initial'),
        ('ligand', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinconformationtemplatestructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='proteinconformation',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='proteinconformation',
            name='protein_anomalies',
            field=models.ManyToManyField(to='protein.ProteinAnomaly'),
        ),
        migrations.AddField(
            model_name='proteinconformation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinState'),
        ),
        migrations.AddField(
            model_name='proteinconformation',
            name='template_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='proteinanomalyruleset',
            name='protein_anomaly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='protein.ProteinAnomaly'),
        ),
        migrations.AddField(
            model_name='proteinanomalyrule',
            name='generic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueGenericNumber'),
        ),
        migrations.AddField(
            model_name='proteinanomalyrule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='protein.ProteinAnomalyRuleSet'),
        ),
        migrations.AddField(
            model_name='proteinanomaly',
            name='anomaly_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinAnomalyType'),
        ),
        migrations.AddField(
            model_name='proteinanomaly',
            name='generic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueGenericNumber'),
        ),
        migrations.AddField(
            model_name='proteinalias',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='protein',
            name='endogenous_ligands',
            field=models.ManyToManyField(to='ligand.Ligand'),
        ),
        migrations.AddField(
            model_name='protein',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinFamily'),
        ),
        migrations.AddField(
            model_name='protein',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='protein',
            name='residue_numbering_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueNumberingScheme'),
        ),
        migrations.AddField(
            model_name='protein',
            name='sequence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinSequenceType'),
        ),
        migrations.AddField(
            model_name='protein',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinSource'),
        ),
        migrations.AddField(
            model_name='protein',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Species'),
        ),
        migrations.AddField(
            model_name='protein',
            name='states',
            field=models.ManyToManyField(through='protein.ProteinConformation', to='protein.ProteinState'),
        ),
        migrations.AddField(
            model_name='protein',
            name='web_links',
            field=models.ManyToManyField(to='common.WebLink'),
        ),
        migrations.AddField(
            model_name='identifiedsites',
            name='protein_conformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_protein_conformation', to='protein.ProteinConformation'),
        ),
        migrations.AddField(
            model_name='identifiedsites',
            name='residues',
            field=models.ManyToManyField(related_name='site_residue', to='residue.Residue'),
        ),
        migrations.AddField(
            model_name='identifiedsites',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Site'),
        ),
        migrations.AddField(
            model_name='gene',
            name='proteins',
            field=models.ManyToManyField(related_name='genes', to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='gene',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='proteinanomaly',
            unique_together={('anomaly_type', 'generic_number')},
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('name', 'species', 'position')},
        ),
    ]
