# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20160901_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together=set([('name', 'species', 'position')]),
        ),
    ]
