# Generated by Django 2.0.4 on 2018-08-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20180117_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='residue_numbering_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.ResidueNumberingScheme'),
        ),
    ]
