# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20160111_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinGProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.TextField(null=True)),
            ],
            options={
                'db_table': 'protein_gprotein',
            },
        ),
        migrations.CreateModel(
            name='ProteinGProteinPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transduction', models.TextField(null=True)),
                ('g_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.ProteinGProtein')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'protein_gprotein_pair',
            },
        ),
        migrations.AddField(
            model_name='proteingprotein',
            name='proteins',
            field=models.ManyToManyField(through='protein.ProteinGProteinPair', to='protein.Protein'),
        ),
    ]
