# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20160926_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteingprotein',
            name='sequence',
        ),
        migrations.AddField(
            model_name='proteingprotein',
            name='slug',
            field=models.SlugField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
