# Generated by Django 2.0.8 on 2019-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20180809_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingproteinpair',
            name='log_rai_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='log_rai_sem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
