# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20171002_1254'),
        ('protein', '0003_auto_20171103_1041'),
    ]

    operations = [
    ]
