# Generated by Django 2.0.8 on 2019-03-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_auto_20190302_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingproteinpair',
            name='g_protein_subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gprotein', to='protein.Protein'),
        ),
    ]
