# Generated by Django 2.0.4 on 2019-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_proteingproteinpair_g_protein_subunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteinconformation',
            name='template_structure',
        ),
    ]
