# Generated by Django 2.0.8 on 2019-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0006_remove_proteinconformation_template_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingproteinpair',
            name='references',
            field=models.ManyToManyField(to='common.Publication'),
        ),
    ]
