# Generated by Django 3.0.4 on 2020-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_proteingproteinpair_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingproteinpair',
            name='emax_dnorm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='emax_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='emax_sem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='log_ec50_dnorm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='log_ec50_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='log_ec50_sem',
            field=models.FloatField(null=True),
        ),
    ]
