# Generated by Django 3.0.2 on 2020-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200511_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingproteinpair',
            name='emax_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='logmaxec50_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='pec50_deg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
