# Generated by Django 3.0.2 on 2021-02-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citation_page_name'),
        ('protein', '0010_auto_20201116_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinArrestinPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('emax_deg', models.FloatField(blank=True, null=True)),
                ('pec50_deg', models.FloatField(blank=True, null=True)),
                ('logmaxec50_deg', models.FloatField(blank=True, null=True)),
                ('arrestin_subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrestin', to='protein.Protein')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
                ('references', models.ManyToManyField(to='common.Publication')),
            ],
            options={
                'db_table': 'protein_arrestin_pair',
            },
        ),
    ]
