# Generated by Django 3.1.7 on 2021-08-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0012_auto_20210308_1819'),
        ('protein', '0012_auto_20210226_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteingproteinpair',
            old_name='emax_deg',
            new_name='emax',
        ),
        migrations.RenameField(
            model_name='proteingproteinpair',
            old_name='emax_dnorm',
            new_name='logmaxec50',
        ),
        migrations.RenameField(
            model_name='proteingproteinpair',
            old_name='emax_mean',
            new_name='pec50',
        ),
        migrations.RenameField(
            model_name='proteingproteinpair',
            old_name='emax_sem',
            new_name='stand_dev',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='log_rai_mean',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='log_rai_sem',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='logmaxec50_deg',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='pec50_deg',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='pec50_dnorm',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='pec50_mean',
        ),
        migrations.RemoveField(
            model_name='proteingproteinpair',
            name='pec50_sem',
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand'),
        ),
        migrations.AddField(
            model_name='proteingproteinpair',
            name='variant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteingproteinpair',
            name='g_protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinfamily'),
        ),
        migrations.DeleteModel(
            name='ProteinGProtein',
        ),
    ]
