# Generated by Django 3.1.7 on 2021-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0014_auto_20210816_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteincouplings',
            name='physiological_ligand',
            field=models.BooleanField(default=False),
        ),
    ]
