# Generated by Django 2.2.1 on 2022-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0015_proteincouplings_physiological_ligand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteinfusionprotein',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='proteinfusionprotein',
            name='protein_fusion',
        ),
        migrations.RemoveField(
            model_name='proteinfusionprotein',
            name='segment_after',
        ),
        migrations.RemoveField(
            model_name='proteinfusionprotein',
            name='segment_before',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='endogenous_ligands',
        ),
        migrations.DeleteModel(
            name='ProteinFusion',
        ),
        migrations.DeleteModel(
            name='ProteinFusionProtein',
        ),
    ]
