# Generated by Django 2.2.17 on 2024-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteincouplings',
            name='emax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteincouplings',
            name='pec50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
