# Generated by Django 3.2.18 on 2024-02-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adipose_tissue', models.FloatField(blank=True, null=True)),
                ('adrenal_gland', models.FloatField(blank=True, null=True)),
                ('amygdala', models.FloatField(blank=True, null=True)),
                ('appendix', models.FloatField(blank=True, null=True)),
                ('basal_ganglia', models.FloatField(blank=True, null=True)),
                ('bone_marrow', models.FloatField(blank=True, null=True)),
                ('breast', models.FloatField(blank=True, null=True)),
                ('cerebellum', models.FloatField(blank=True, null=True)),
                ('cerebral_cortex', models.FloatField(blank=True, null=True)),
                ('cervix', models.FloatField(blank=True, null=True)),
                ('choroid_plexus', models.FloatField(blank=True, null=True)),
                ('colon', models.FloatField(blank=True, null=True)),
                ('duodenum', models.FloatField(blank=True, null=True)),
                ('endometrium', models.FloatField(blank=True, null=True)),
                ('epididymis', models.FloatField(blank=True, null=True)),
                ('esophagus', models.FloatField(blank=True, null=True)),
                ('fallopian_tube', models.FloatField(blank=True, null=True)),
                ('gallbladder', models.FloatField(blank=True, null=True)),
                ('heart_muscle', models.FloatField(blank=True, null=True)),
                ('hippocampal_formation', models.FloatField(blank=True, null=True)),
                ('hypothalamus', models.FloatField(blank=True, null=True)),
                ('kidney', models.FloatField(blank=True, null=True)),
                ('liver', models.FloatField(blank=True, null=True)),
                ('lung', models.FloatField(blank=True, null=True)),
                ('lymph_node', models.FloatField(blank=True, null=True)),
                ('midbrain', models.FloatField(blank=True, null=True)),
                ('ovary', models.FloatField(blank=True, null=True)),
                ('pancreas', models.FloatField(blank=True, null=True)),
                ('parathyroid_gland', models.FloatField(blank=True, null=True)),
                ('pituitary_gland', models.FloatField(blank=True, null=True)),
                ('placenta', models.FloatField(blank=True, null=True)),
                ('prostate', models.FloatField(blank=True, null=True)),
                ('rectum', models.FloatField(blank=True, null=True)),
                ('retina', models.FloatField(blank=True, null=True)),
                ('salivary_gland', models.FloatField(blank=True, null=True)),
                ('seminal_vesicle', models.FloatField(blank=True, null=True)),
                ('skeletal_muscle', models.FloatField(blank=True, null=True)),
                ('skin', models.FloatField(blank=True, null=True)),
                ('small_intestine', models.FloatField(blank=True, null=True)),
                ('smooth_muscle', models.FloatField(blank=True, null=True)),
                ('spinal_cord', models.FloatField(blank=True, null=True)),
                ('spleen', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('testis', models.FloatField(blank=True, null=True)),
                ('thymus', models.FloatField(blank=True, null=True)),
                ('thyroid_gland', models.FloatField(blank=True, null=True)),
                ('tongue', models.FloatField(blank=True, null=True)),
                ('tonsil', models.FloatField(blank=True, null=True)),
                ('urinary_bladder', models.FloatField(blank=True, null=True)),
                ('vagina', models.FloatField(blank=True, null=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
        migrations.CreateModel(
            name='CancerPrognostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=100)),
                ('max_expression', models.CharField(max_length=30)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
