# Generated by Django 3.0.3 on 2024-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinsegment',
            name='domain',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
