# Generated by Django 2.2.17 on 2025-01-10 08:26


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0019_proteinsegment_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteincouplings',
            name='emax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteincouplings',
            name='pec50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
