# Generated by Django 2.2.17 on 2025-01-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0019_auto_20240305_1848'),
        ('protein', '0019_proteinsegment_domain'),
    ]

    operations = [
    ]
