# Generated by Django 3.0.3 on 2024-02-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0019_auto_20240212_1544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tissueexpression',
            table='TissueExpression',
        ),
    ]
