# Generated by Django 3.0.3 on 2024-02-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20240223_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tissueexpression',
            table='tissue_expression',
        ),
    ]
