# Generated by Django 2.2.17 on 2026-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20250318_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteincouplings',
            name='emax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteincouplings',
            name='pec50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
