# Generated by Django 2.2.17 on 2026-03-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20250828_1656'),
        ('protein', '0021_auto_20260108_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='entrez_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='entrez_weblink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink'),
        ),
    ]
