# Generated by Django 2.2.17 on 2026-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0022_auto_20260310_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
