# Generated by Django 2.2.17 on 2026-01-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protein", "0023_auto_20260830_0735"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteinFamilyClassificationSense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "protein_family_classification_sense",
            },
        ),
        migrations.CreateModel(
            name="ProteinFamilyClassificationChemotype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "protein_family_classification_chemotype",
            },
        ),
        migrations.CreateModel(
            name="ProteinFamilyClassificationModality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "protein_family_classification_modality",
            },
        ),
        migrations.CreateModel(
            name="ProteinFamilyClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protein_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protein.ProteinFamily",
                    ),
                ),
                (
                    "sense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protein.ProteinFamilyClassificationSense",
                    ),
                ),
                (
                    "chemotype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protein.ProteinFamilyClassificationChemotype",
                    ),
                ),
                ("chemotype_order", models.SmallIntegerField(blank=True, null=True)),
                (
                    "modality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protein.ProteinFamilyClassificationModality",
                    ),
                ),
                ("modality_order", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "protein_family_classification",
            },
        ),
        migrations.AddConstraint(
            model_name="proteinfamilyclassification",
            constraint=models.CheckConstraint(
                check=models.Q(chemotype_order__isnull=True)
                | models.Q(chemotype_order__in=[1, 2]),
                name="pfc_chemotype_order_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="proteinfamilyclassification",
            constraint=models.CheckConstraint(
                check=models.Q(modality_order__isnull=True)
                | models.Q(modality_order__in=[1, 2]),
                name="pfc_modality_order_valid",
            ),
        ),
    ]
